"""Generate test data for the Correlator modules (rtl/Correlator/).

Covered so far: Internal/cmac_acc, cmac, dual_pol_cmac, auto_tap, baseline_tap,
Internal/x_cast, Internal/read_ctrl, Internal/write_ctrl, xeng_descramble,
xeng_descramble_4ant, xeng, cross_multiplier, xeng_tvg.

Cycle-level models of the casper_library_correlator.slx diagrams. Row i of
every CSV is the value driven before / read after clock edge i (pre-edge
read convention): outputs come from the state before edge i and the inputs
of cycle i. All words are raw unsigned bit patterns, written as decimal
Python integers (dual_pol_cmac words exceed 64 bits).

Besides the structural models, every cmac / dual_pol_cmac set is checked
behaviourally: after a sync at S, the dump 2 cycles after each rst at
S + MULT + ADD + 1 + k*ACC_LEN (k >= 1) must be the exact sum of
a·conj(b) over the ACC_LEN samples S+1+(k-1)*ACC_LEN ..., with
valid_out = 1, and between dumps acc_out / valid_out relay acc_in /
valid_in with a 2-cycle delay.
"""

import json
import math
import random
import sys

from common import TEST_DATA_ROOT, run_cli

SCRIPT = "gen_correlator_test_data.py"
CATEGORY = "Correlator"


# ── helpers ──────────────────────────────────────────────────────────────────
def s(x, n):
    """Raw n-bit word -> signed int."""
    x &= (1 << n) - 1
    return x - (1 << n) if x >> (n - 1) else x


def u(x, n):
    return x & ((1 << n) - 1)


def pack(parts, n):
    """[p0, p1, ...] signed ints -> raw word, p0 in the MSBs."""
    w = 0
    for p in parts:
        w = (w << n) | u(p, n)
    return w


def unpack(w, n, k):
    """Raw word -> k signed parts, MSB part first."""
    return [s(w >> (n * (k - 1 - i)), n) for i in range(k)]


def delayed(seq, d, fill=0):
    return [fill] * d + seq[:len(seq) - d] if d else list(seq)


def write_set(d, params, ports):
    d.mkdir(parents=True, exist_ok=True)
    (d / "params.json").write_text(json.dumps(params, indent=2) + "\n")
    for name, vals in ports.items():
        vals = list(vals)
        if vals and isinstance(vals[0], list):
            # array port: one file per element, sim_<name><j>.csv = element j
            for j in range(len(vals[0])):
                (d / f"sim_{name}{j}.csv").write_text("".join(f"{int(v[j])}\n" for v in vals))
        else:
            (d / f"sim_{name}.csv").write_text("".join(f"{int(v)}\n" for v in vals))


def toml_block(dir_, top, sets):
    lines = [f"# test {top}", "[[simulations]]", f'dir = "{dir_}"', f'top = "{top}"',
             f'test_data_script = "{SCRIPT}"']
    for p, desc in sets:
        lines += [f"# {desc}", "[[simulations.parameters]]"]
        lines += [f"{k} = {v}" for k, v in p.items()]
    return "\n".join(lines)


def write_md(mdir, top, prose, sets, cycles):
    keys = list(sets[0][0].keys())
    lines = [f"# {top} test data", "", prose, "",
             f"Generated by `test_data/scripts/{SCRIPT}` from a cycle-level model of the "
             "casper_library diagram (not exported from MATLAB). Each `simdataN/` holds "
             "`params.json` (the testbench matches it against the DUT parameters) and one "
             "`sim_<port>.csv` per port: raw unsigned words in decimal, row i = value "
             "driven before / read after clock edge i.", "",
             "| Test # | Directory | " + " | ".join(keys) + " | Cycles | Description |",
             "|" + "---|" * (len(keys) + 4)]
    for n, (p, desc) in enumerate(sets):
        lines.append(f"| {n} | `simdata{n}` | " + " | ".join(str(p[k]) for k in keys)
                     + f" | {cycles[n]} | {desc} |")
    (mdir / "test_data.md").write_text("\n".join(lines) + "\n")


# ── cmac_acc ─────────────────────────────────────────────────────────────────
def m_cmac_acc(n, rst, din, acc_in, valid_in):
    """Raw words in, (acc_out, valid_out) raw words out."""
    q = 0
    pd = [0, 0]
    pv = [0, 0]
    acc_out, valid_out = [], []
    for r, x, ai, vi in zip(rst, din, acc_in, valid_in):
        acc_out.append(pd[1])
        valid_out.append(pv[1])
        pd = [q if r else ai, pd[0]]
        pv = [1 if r else vi, pv[0]]
        q = x if r else u(q + x, n)
    return acc_out, valid_out


def gen_cmac_acc():
    mdir = TEST_DATA_ROOT / CATEGORY / "Internal" / "cmac_acc"
    specs = [(dict(N_BITS=16), "16-bit, random rst (single, back-to-back, long gaps)"),
             (dict(N_BITS=6), "6-bit: the accumulator wraps"),
             (dict(N_BITS=1), "1-bit")]
    sets, cycles = [], []
    for k, (p, desc) in enumerate(specs):
        rng = random.Random(f"cmac_acc-{k}")
        n, cyc = p["N_BITS"], 400
        rst = [0] * cyc
        t = 3
        while t < cyc:
            rst[t] = 1
            t += rng.choice([1, 2, 5, 17, 40])
        din = [rng.randrange(1 << n) for _ in range(cyc)]
        acc_in = [rng.randrange(1 << n) for _ in range(cyc)]
        valid_in = [rng.randrange(2) for _ in range(cyc)]
        acc_out, valid_out = m_cmac_acc(n, rst, din, acc_in, valid_in)
        write_set(mdir / f"simdata{k}", p, dict(rst=rst, din=din, acc_in=acc_in,
                                                valid_in=valid_in, acc_out=acc_out,
                                                valid_out=valid_out))
        sets.append((p, desc))
        cycles.append(cyc)
    write_md(mdir, "cmac_acc",
             "`cmac_acc` is the accumulate-and-relay cell of `cmac` (`system_871`/`886`): "
             "`q <= rst ? din : q + din` (Xilinx Accumulator with hasbypass), "
             "`acc_out = rst ? q : acc_in` and `valid_out = rst ? 1 : valid_in`, both "
             "delayed 2 cycles.", sets, cycles)
    return toml_block("Correlator/Internal", "cmac_acc", sets)


# ── cmac ─────────────────────────────────────────────────────────────────────
def cmac_widths(p):
    bg = math.ceil(math.log2(p["ACC_LEN"]))
    return bg, p["N_BITS_A"] + p["N_BITS_B"] + 1 + bg


def m_cmac(p, a, b, acc_in, sync, valid_in):
    """Structural model of cmac. Returns (acc_out, valid_out, rst)."""
    na, nb = p["N_BITS_A"], p["N_BITS_B"]
    bg, m = cmac_widths(p)
    lat = p["MULT_LATENCY"] + p["ADD_LATENCY"]
    # cmult: a·conj(b), exact, latency lat (power-on 0)
    pre, pim = [], []
    for x, y in zip(a, b):
        ar, ai = unpack(x, na, 2)
        br, bi = unpack(y, nb, 2)
        pre.append(u(ar * br + ai * bi, m))
        pim.append(u(ai * br - ar * bi, m))
    pre, pim = delayed(pre, lat), delayed(pim, lat)
    # sync -> Delay(lat-1) -> Counter -> (cnt == 0, latency 1)
    sync_d = delayed(sync, lat - 1)
    cnt, rst, prev_zero = 0, [], 0
    for sd in sync_d:
        rst.append(prev_zero)
        prev_zero = int(cnt == 0)
        cnt = 0 if sd or cnt == p["ACC_LEN"] - 1 else cnt + 1
    ai_re = [w >> m for w in acc_in]
    ai_im = [u(w, m) for w in acc_in]
    re, _ = m_cmac_acc(m, rst, pre, ai_re, [0] * len(a))
    im, valid_out = m_cmac_acc(m, rst, pim, ai_im, valid_in)
    return [(r << m) | i for r, i in zip(re, im)], valid_out, rst


def check_cmac(p, a, b, acc_in, sync, valid_in, acc_out, valid_out, rst):
    """Behavioural check of the dumps after the first sync (see module doc)."""
    na, nb = p["N_BITS_A"], p["N_BITS_B"]
    _, m = cmac_widths(p)
    L, lat = p["ACC_LEN"], p["MULT_LATENCY"] + p["ADD_LATENCY"]
    syncs = [t for t, v in enumerate(sync) if v]
    S = syncs[0]
    nxt = syncs[1] if len(syncs) > 1 else len(a)
    dumps = {S + lat + 1 + k * L + 2 for k in range(1, len(a))}
    checked = 0
    for t in range(S + lat + 3, min(len(a), nxt + lat + 1)):
        if t == S + lat + 3:
            # first rst after sync: dumps the partial sum from before sync
            assert valid_out[t] == 1, (p, t)
        elif t in dumps:
            k = (t - 2 - (S + lat + 1)) // L
            first = S + 1 + (k - 1) * L
            sre = sim = 0
            for j in range(first, first + L):
                ar, ai = unpack(a[j], na, 2)
                br, bi = unpack(b[j], nb, 2)
                sre += ar * br + ai * bi
                sim += ai * br - ar * bi
            assert (acc_out[t], valid_out[t]) == (pack([sre, sim], m), 1), (p, t)
            checked += 1
        else:
            assert (acc_out[t], valid_out[t]) == (acc_in[t - 2], valid_in[t - 2]), (p, t)
    assert checked >= 3, (p, checked)
    return checked


def cmac_stim(rng, p, cyc, syncs):
    na, nb = p["N_BITS_A"], p["N_BITS_B"]
    _, m = cmac_widths(p)
    L = p["ACC_LEN"]
    a, b = [], []
    for t in range(cyc):
        if syncs[0] + 1 + L <= t < syncs[0] + 1 + 2 * L:
            # one whole integration of most-negative inputs: maximum growth
            a.append(pack([-(1 << (na - 1))] * 2, na))
            b.append(pack([-(1 << (nb - 1))] * 2, nb))
        else:
            a.append(rng.randrange(1 << 2 * na))
            b.append(rng.randrange(1 << 2 * nb))
    acc_in = [rng.randrange(1 << 2 * m) for _ in range(cyc)]
    valid_in = [rng.randrange(2) for _ in range(cyc)]
    sync = [int(t in syncs) for t in range(cyc)]
    return a, b, acc_in, sync, valid_in


CMAC_KEYS = ["ACC_LEN", "N_BITS_A", "BIN_PT_A", "N_BITS_B", "BIN_PT_B",
             "MULT_LATENCY", "ADD_LATENCY", "MULTIPLIER_IMPLEMENTATION"]


def P(keys, vals):
    return dict(zip(keys, vals))


def gen_cmac():
    mdir = TEST_DATA_ROOT / CATEGORY / "cmac"
    specs = [
        (P(CMAC_KEYS, [128, 4, 3, 4, 3, 1, 1, 2]), "Mask defaults: acc_len 128, Fix_4_3, latency 1+1"),
        (P(CMAC_KEYS, [4, 4, 3, 4, 3, 1, 0, 2]), "acc_len 4, add latency 0 (sync delay 0)"),
        (P(CMAC_KEYS, [10, 8, 7, 8, 7, 3, 2, 0]), "acc_len 10 (not a power of 2), Fix_8_7, latency 3+2"),
        (P(CMAC_KEYS, [16, 6, 5, 8, 7, 0, 1, 1]), "Unequal widths Fix_6_5 × Fix_8_7, mult latency 0"),
        (P(CMAC_KEYS, [2, 4, 3, 4, 3, 2, 1, 2]), "Smallest acc_len 2"),
    ]
    sets, cycles = [], []
    for k, (p, desc) in enumerate(specs):
        rng = random.Random(f"cmac-{k}")
        L = p["ACC_LEN"]
        cyc = 6 * L + 60 if L > 16 else 400
        s0 = 7
        # a second sync, not aligned to the integration grid, realigns the rst phase
        syncs = [s0, s0 + 4 * L + 3] if L > 16 else [s0, s0 + 9 * L + 1 + (L // 2)]
        a, b, acc_in, sync, valid_in = cmac_stim(rng, p, cyc, syncs)
        acc_out, valid_out, rst = m_cmac(p, a, b, acc_in, sync, valid_in)
        check_cmac(p, a, b, acc_in, sync, valid_in, acc_out, valid_out, rst)
        write_set(mdir / f"simdata{k}", p, dict(a=a, b=b, acc_in=acc_in, sync=sync,
                                                valid_in=valid_in, acc_out=acc_out,
                                                valid_out=valid_out))
        sets.append((p, desc))
        cycles.append(cyc)
    write_md(mdir, "cmac",
             "`cmac` accumulates `a·conj(b)` over `ACC_LEN` samples and inserts each "
             "integration into the `acc_in` relay. Each set has a sync near the start, a "
             "whole integration of most-negative inputs (maximum bit growth) and a "
             "second, misaligned sync that realigns the integration phase; `acc_in` and "
             "`valid_in` are random. The generator checks every dump against the exact "
             "sum of `a·conj(b)` over its `ACC_LEN` samples, and every other cycle "
             "against the 2-cycle relay of `acc_in` / `valid_in`.", sets, cycles)
    return toml_block(CATEGORY, "cmac", sets)


# ── dual_pol_cmac ────────────────────────────────────────────────────────────
DP_PAIRS = [(0, 0), (1, 1), (0, 1), (1, 0)]  # (a1 pol, a2 pol): XX, YY, XY, YX


def m_dual_pol_cmac(p, a1, a2, acc_in, sync, valid_in, check=True):
    n = p["N_BITS_IN"]
    cp = dict(ACC_LEN=p["ACC_LEN"], N_BITS_A=n, BIN_PT_A=n - 1, N_BITS_B=n,
              BIN_PT_B=n - 1, MULT_LATENCY=p["MULT_LATENCY"], ADD_LATENCY=p["ADD_LATENCY"])
    _, m = cmac_widths(cp)
    outs, valid_out = [], None
    for c, (pa, pb) in enumerate(DP_PAIRS):
        a = [(w >> (2 * n * (1 - pa))) & ((1 << 2 * n) - 1) for w in a1]
        b = [(w >> (2 * n * (1 - pb))) & ((1 << 2 * n) - 1) for w in a2]
        ai = [(w >> (2 * m * (3 - c))) & ((1 << 2 * m) - 1) for w in acc_in]
        vi = valid_in if c == 3 else [0] * len(a1)
        o, v, _ = m_cmac(cp, a, b, ai, sync, vi)
        if check:
            check_cmac(cp, a, b, ai, sync, vi, o, v, None)
        outs.append(o)
        if c == 3:
            valid_out = v
    acc_out = [(w0 << 6 * m) | (w1 << 4 * m) | (w2 << 2 * m) | w3 for w0, w1, w2, w3 in zip(*outs)]
    return acc_out, valid_out, m


def gen_dual_pol_cmac():
    mdir = TEST_DATA_ROOT / CATEGORY / "dual_pol_cmac"
    keys = ["ACC_LEN", "N_BITS_IN", "BIN_PT_IN", "MULT_LATENCY", "ADD_LATENCY",
            "MULTIPLIER_IMPLEMENTATION"]
    specs = [
        (P(keys, [128, 4, 3, 1, 1, 2]), "Mask defaults: acc_len 128, 4-bit inputs"),
        (P(keys, [8, 4, 3, 2, 1, 2]), "acc_len 8, latency 2+1"),
        (P(keys, [6, 8, 7, 1, 0, 0]), "acc_len 6, 8-bit inputs, add latency 0"),
    ]
    sets, cycles = [], []
    for k, (p, desc) in enumerate(specs):
        rng = random.Random(f"dual_pol_cmac-{k}")
        n, L = p["N_BITS_IN"], p["ACC_LEN"]
        cyc = 6 * L + 60 if L > 16 else 300
        s0 = 5
        syncs = [s0, s0 + 4 * L + 3] if L > 16 else [s0, s0 + 9 * L + 1 + (L // 2)]
        neg = pack([-(1 << (n - 1))] * 4, n)
        a1, a2 = [], []
        for t in range(cyc):
            if s0 + 1 + L <= t < s0 + 1 + 2 * L:
                a1.append(neg)
                a2.append(neg)
            else:
                a1.append(rng.randrange(1 << 4 * n))
                a2.append(rng.randrange(1 << 4 * n))
        m = 2 * n + 1 + math.ceil(math.log2(L))
        acc_in = [rng.randrange(1 << 8 * m) for _ in range(cyc)]
        valid_in = [rng.randrange(2) for _ in range(cyc)]
        sync = [int(t in syncs) for t in range(cyc)]
        acc_out, valid_out, _ = m_dual_pol_cmac(p, a1, a2, acc_in, sync, valid_in)
        write_set(mdir / f"simdata{k}", p, dict(a1=a1, a2=a2, acc_in=acc_in, sync=sync,
                                                valid_in=valid_in, acc_out=acc_out,
                                                valid_out=valid_out))
        sets.append((p, desc))
        cycles.append(cyc)
    write_md(mdir, "dual_pol_cmac",
             "`dual_pol_cmac` runs four `cmac`s on the polarisation products "
             "`{XX, YY, XY, YX}` = `{a1.p0·conj(a2.p0), a1.p1·conj(a2.p1), "
             "a1.p0·conj(a2.p1), a1.p1·conj(a2.p0)}` (p0 in the MSBs of a1/a2; "
             "acc_in/acc_out slices in the same order, XX in the MSBs). Only the YX "
             "cmac sees `valid_in` and drives `valid_out`. Stimulus and the per-cmac "
             "behavioural check are as for `cmac`.", sets, cycles)
    return toml_block(CATEGORY, "dual_pol_cmac", sets)


# ── auto_tap / baseline_tap ──────────────────────────────────────────────────
MULT_IMP = {0: 0, 1: 2, 2: 1}  # tap mult_type -> dual_pol_cmac multiplier_implementation


def m_sync_delay(seq, n):
    """casper sync_delay (rtl/Delays/sync_delay.sv): a pulse restarts the count."""
    if n == 0:
        return list(seq)
    cnt, out = 0, []
    for x in seq:
        out.append(int(cnt == 1))
        cnt = n if x else (cnt - 1 if cnt else 0)
    return out


def tap_dp(p):
    return dict(ACC_LEN=p["ACC_LEN"], N_BITS_IN=p["N_BITS"], BIN_PT_IN=p["N_BITS"] - 1,
                MULT_LATENCY=p["MULT_LATENCY"], ADD_LATENCY=p["ADD_LATENCY"],
                MULTIPLIER_IMPLEMENTATION=MULT_IMP[p["MULT_TYPE"]])


def auto_tap_delays(p):
    n, L = p["N_ANTS"], p["ACC_LEN"]
    d = (L - 1) * math.ceil(n / 2) + math.ceil(n / 2) - n // 2
    s_ = p["ADD_LATENCY"] + p["MULT_LATENCY"] + L + math.floor(n / 2 + 1) + 1
    return d, s_


def m_auto_tap(p, a_del, a_ndel, a_loop, acc_in, valid_in, sync_in, check=True):
    d, s_ = auto_tap_delays(p)
    acc_out, valid_out, _ = m_dual_pol_cmac(tap_dp(p), a_del, a_ndel, acc_in, sync_in,
                                            valid_in, check)
    return dict(a_del_out=list(a_del), a_ndel_out=list(a_ndel), a_end_out=delayed(a_loop, d),
                acc_out=acc_out, valid_out=valid_out, rst_out=list(sync_in),
                sync_out=m_sync_delay(sync_in, s_))


def m_baseline_tap(p, a_del, a_ndel, a_end, acc_in, valid_in, rst, sync1, check=True):
    n, L, sep = p["N_ANTS"], p["ACC_LEN"], p["ANT_SEP"]
    a_del_out = delayed(a_del, L + 1)
    rst_out = delayed(rst, 1)
    cnt, sel = 0, []
    for r in rst:
        sel.append(int(cnt < sep * L))
        cnt = 0 if r or cnt == n * L - 1 else cnt + 1
    a2 = delayed([e if sl else nd for sl, nd, e in zip(sel, a_ndel, a_end)], 1)
    acc_out, valid_out, _ = m_dual_pol_cmac(tap_dp(p), a_del_out, a2, acc_in, rst_out,
                                            valid_in, check)
    return dict(a_del_out=a_del_out, a_ndel_out=delayed(a_ndel, 1), a_end_out=delayed(a_end, 1),
                acc_out=acc_out, valid_out=valid_out, rst_out=rst_out, sync_out=list(sync1))


def m_tap_chain(n_ants, L, ant, sync, bits=4, mult=2, add=1, a_loop_check=True):
    """xeng tap chain (xeng_init.m wiring): auto_tap + floor(N/2) baseline_taps,
    tapK.a_del_out looped back to auto_tap.a_loop. Returns the per-tap outputs."""
    base = dict(N_ANTS=n_ants, N_BITS=bits, ACC_LEN=L, ADD_LATENCY=add, MULT_LATENCY=mult,
                MULT_TYPE=0)
    k_taps = n_ants // 2
    zeros = [0] * len(ant)
    # a_del path first: it does not depend on the loop
    a_del = [list(ant)]
    for k in range(1, k_taps + 1):
        a_del.append(delayed(a_del[-1], L + 1))
    taps = [m_auto_tap(dict(base), ant, ant, a_del[-1], zeros, zeros, sync, check=False)]
    for k in range(1, k_taps + 1):
        prev = taps[-1]
        taps.append(m_baseline_tap(dict(base, ANT_SEP=k), prev["a_del_out"], prev["a_ndel_out"],
                                   prev["a_end_out"], prev["acc_out"], prev["valid_out"],
                                   prev["rst_out"], prev["sync_out"], check=False))
    return taps


def check_tap_chain(n_ants, L, frames=4, seed=0):
    """Composition check of the tap models, ahead of xeng (C6):

    * a_end_out of the auto_tap lags the antenna stream by exactly N_ANTS*ACC_LEN;
    * every integration a tap feeds into the relay pairs two antennas' samples
      of the same time samples (same frame, same sample index), i.e. it is a
      baseline visibility, and per frame the taps produce N_ANTS*(N_ANTS/2+1)
      of them covering every baseline.

    The antenna stream is frame-major: frame f, antenna j, sample s at cycle
    S + 1 + (f*N_ANTS + j)*ACC_LEN + s. Each sample word encodes (f, j, s) so
    the paired samples can be read back from the cmac inputs.
    """
    rng = random.Random(seed)
    n = n_ants
    S = 3
    cyc = S + 1 + (frames + 2) * n * L
    bits = 2 * max(8, (frames * n * L).bit_length() + 2)
    # tag: one polarisation's re = index (f*N + j)*L + s, so products identify samples
    ant, tag = [], {}
    for t in range(cyc):
        i = t - (S + 1)
        ant.append(i if i >= 0 else 0)
    taps = m_tap_chain(n, L, ant, [int(t == S) for t in range(cyc)], bits=bits)
    assert taps[0]["a_end_out"] == delayed(ant, n * L), "loop delay != N_ANTS*ACC_LEN"
    # replay the cmac inputs of every tap and check the pairing of each window
    k_taps = n // 2
    pairs = {}
    for k in range(k_taps + 1):
        if k == 0:
            a1, a2, sy = ant, ant, [int(t == S) for t in range(cyc)]
        else:
            a1 = delayed(ant, k * (L + 1))
            prev_ndel = delayed(ant, k - 1)
            prev_end = delayed(ant, n * L + k - 1)
            rst = delayed([int(t == S) for t in range(cyc)], k - 1)
            cnt, sel = 0, []
            for r in rst:
                sel.append(int(cnt < k * L))
                cnt = 0 if r or cnt == n * L - 1 else cnt + 1
            a2 = delayed([e if sl else nd for sl, nd, e in zip(sel, prev_ndel, prev_end)], 1)
            sy = delayed(rst, 1)
        start = sy.index(1) + 1                 # cmac frame start
        for w in range(1, frames * n):          # integration windows (skip the first)
            idx1 = [a1[start + w * L + s_] for s_ in range(L)]
            idx2 = [a2[start + w * L + s_] for s_ in range(L)]
            if 0 in idx1 or 0 in idx2:
                continue                        # touches the power-on zeros
            fj1 = {(i // L) for i in idx1}
            fj2 = {(i // L) for i in idx2}
            ss1 = [i % L for i in idx1]
            ss2 = [i % L for i in idx2]
            assert len(fj1) == 1 and len(fj2) == 1 and ss1 == ss2 == list(range(L)), (n, L, k, w)
            (b1,), (b2,) = fj1, fj2
            f1, j1 = divmod(b1, n)
            f2, j2 = divmod(b2, n)
            assert f1 == f2, f"tap {k} window {w} pairs frames {f1} and {f2}"
            pairs.setdefault(f1, []).append((k, j1, j2))
    for f, lst in pairs.items():
        if len(lst) == n * (k_taps + 1):
            base = {tuple(sorted((j1, j2))) for _, j1, j2 in lst}
            assert base == {(x, y) for x in range(n) for y in range(x, n)}, (n, L, f, lst)
    return pairs


def tap_stim(rng, n_bits, cyc, frame, s0, n_ants_frames_neg=True):
    w = 4 * n_bits
    neg = pack([-(1 << (n_bits - 1))] * 4, n_bits)
    out = []
    for t in range(cyc):
        out.append(neg if s0 + 1 + frame <= t < s0 + 1 + 2 * frame else rng.randrange(1 << w))
    # cycle 0 is read at the t = 0 edge, before the first inputs reach the
    # combinational pass-through outputs: keep it 0
    out[0] = 0
    return out


def gen_auto_tap():
    mdir = TEST_DATA_ROOT / CATEGORY / "auto_tap"
    keys = ["N_ANTS", "N_SIMULTAN", "N_BITS", "ACC_LEN", "ADD_LATENCY", "MULT_LATENCY",
            "BRAM_LATENCY", "MULT_TYPE", "USE_BRAM_DELAY"]
    specs = [
        (P(keys, [4, 2, 4, 64, 1, 2, 2, 0, 1]), "Mask defaults: D = 126, S = 71 (the stored DelayLen values)"),
        (P(keys, [4, 2, 4, 8, 1, 2, 2, 1, 0]), "acc_len 8, delay_slr (D = 14, S = 15)"),
        (P(keys, [5, 2, 4, 4, 0, 1, 2, 2, 1]), "Odd N_ANTS 5: D = 3*3 + 1 = 10, S = 9"),
        (P(keys, [2, 2, 8, 4, 1, 1, 1, 0, 1]), "N_ANTS 2, 8-bit inputs: D = 3, S = 9"),
    ]
    sets, cycles = [], []
    for k, (p, desc) in enumerate(specs):
        rng = random.Random(f"auto_tap-{k}")
        n, L, nb = p["N_ANTS"], p["ACC_LEN"], p["N_BITS"]
        frame = n * L
        cyc = max(4 * frame + 60, 400)
        s0 = 5
        syncs = [s0, s0 + 2 * frame + 3]
        a_del = tap_stim(rng, nb, cyc, L, s0)
        a_ndel = tap_stim(rng, nb, cyc, L, s0)
        a_loop = [rng.randrange(1 << 4 * nb) for _ in range(cyc)]
        m = 2 * nb + 1 + math.ceil(math.log2(L))
        acc_in = [rng.randrange(1 << 8 * m) for _ in range(cyc)]
        valid_in = [rng.randrange(2) for _ in range(cyc)]
        sync_in = [int(t in syncs) for t in range(cyc)]
        out = m_auto_tap(p, a_del, a_ndel, a_loop, acc_in, valid_in, sync_in)
        if k == 0:
            assert auto_tap_delays(p) == (126, 71)
        write_set(mdir / f"simdata{k}", p, dict(a_del=a_del, a_ndel=a_ndel, a_loop=a_loop,
                                                acc_in=acc_in, valid_in=valid_in,
                                                sync_in=sync_in, **out))
        sets.append((p, desc))
        cycles.append(cyc)
    write_md(mdir, "auto_tap",
             "`auto_tap` passes `a_del`, `a_ndel` and `sync_in` (as `rst_out`) straight "
             "through, integrates `a_del·conj(a_ndel)` per polarisation product in a "
             "`dual_pol_cmac`, delays `a_loop` by `D = (ACC_LEN-1)*ceil(N_ANTS/2) + "
             "N_ANTS%2` and `sync_in` by `S = ADD + MULT + ACC_LEN + floor(N_ANTS/2+1) + 1` "
             "(`sync_delay`). All inputs are random except one integration of "
             "most-negative samples; there are two syncs. The generator also checks the "
             "tap chain composition (see `baseline_tap/test_data.md`).", sets, cycles)
    return toml_block(CATEGORY, "auto_tap", sets)


def gen_baseline_tap():
    mdir = TEST_DATA_ROOT / CATEGORY / "baseline_tap"
    keys = ["N_ANTS", "ANT_SEP", "N_BITS", "ACC_LEN", "ADD_LATENCY", "MULT_LATENCY",
            "BRAM_LATENCY", "MULT_TYPE", "USE_BRAM_DELAY"]
    specs = [
        (P(keys, [4, 1, 4, 32, 1, 2, 2, 2, 1]), "Mask defaults"),
        (P(keys, [4, 2, 4, 8, 1, 2, 2, 1, 1]), "ANT_SEP 2: a_end for the first half of each frame"),
        (P(keys, [6, 3, 4, 4, 1, 1, 2, 0, 0]), "6 antennas, ANT_SEP 3, delay_slr, acc_len 4"),
        (P(keys, [5, 2, 8, 6, 0, 1, 1, 0, 1]), "5 antennas, acc_len 6 (not a power of 2), 8-bit"),
    ]
    sets, cycles = [], []
    for k, (p, desc) in enumerate(specs):
        rng = random.Random(f"baseline_tap-{k}")
        n, L, nb = p["N_ANTS"], p["ACC_LEN"], p["N_BITS"]
        frame = n * L
        cyc = max(4 * frame + 60, 400)
        s0 = 5
        rsts = [s0, s0 + 2 * frame + 3]
        a_del = tap_stim(rng, nb, cyc, L, s0)
        a_ndel = tap_stim(rng, nb, cyc, L, s0)
        a_end = tap_stim(rng, nb, cyc, L, s0)
        m = 2 * nb + 1 + math.ceil(math.log2(L))
        acc_in = [rng.randrange(1 << 8 * m) for _ in range(cyc)]
        valid_in = [rng.randrange(2) for _ in range(cyc)]
        rst = [int(t in rsts) for t in range(cyc)]
        sync1 = [0] + [rng.randrange(2) for _ in range(cyc - 1)]
        out = m_baseline_tap(p, a_del, a_ndel, a_end, acc_in, valid_in, rst, sync1)
        write_set(mdir / f"simdata{k}", p, dict(a_del=a_del, a_ndel=a_ndel, a_end=a_end,
                                                acc_in=acc_in, valid_in=valid_in, rst=rst,
                                                sync1=sync1, **out))
        sets.append((p, desc))
        cycles.append(cyc)
    chains = [(4, 8), (4, 4), (2, 8), (3, 4), (5, 4), (6, 4), (8, 2)]
    for n, L in chains:
        check_tap_chain(n, L)
    write_md(mdir, "baseline_tap",
             "`baseline_tap` delays `a_del` by `ACC_LEN+1` (that is its cmac `a1`) and "
             "`a_ndel`, `a_end`, `rst` by 1. A counter reset by `rst` selects the cmac's "
             "conjugated input: `a_end` for the first `ANT_SEP*ACC_LEN` samples of each "
             "`N_ANTS*ACC_LEN` frame, `a_ndel` afterwards (latency-1 Mux). `sync1` passes "
             "straight through. Inputs are random apart from one integration of "
             "most-negative samples; there are two rst pulses. Besides these unit sets, "
             "the generator chains its auto_tap and baseline_tap models the way xeng does "
             "(N_ANTS/ACC_LEN = " + ", ".join(f"{n}/{L}" for n, L in chains) + ") and "
             "checks that the loop delay is exactly `N_ANTS*ACC_LEN` and that every "
             "integration pairs the same time samples of two antennas of one frame, "
             "covering every baseline.", sets, cycles)
    return toml_block(CATEGORY, "baseline_tap", sets)


# ── xeng_descramble and its internals ────────────────────────────────────────
def desc_params(n_ants, n_bits, acc_len, demux):
    """xeng_descramble mask initialization (system_root.xml, Block 411)."""
    n, L, d = n_ants, acc_len, demux
    T = n // 2 + 1
    NV = n * T
    E = n * (n + 1) // 2
    W = 2 * n_bits + int(math.floor(math.log2(L))) + 1
    P = 1 << math.ceil(math.log2(W))
    dl = (L * n) // NV // d - 1
    DEL = max(dl, 0)
    CNT = d * E - 1 if DEL == 0 else d * E
    return dict(N=n, T=T, NV=NV, E=E, PIVOT=n // 2 * T + T * n // 4, W=W, P=P, OW=8 * P // d,
                D=d, DEL=DEL, CNT=CNT, DEL_BITS=max(1, math.ceil(math.log2(DEL + 1))),
                RD_BITS=math.ceil(math.log2(CNT + 1)), WA_BITS=math.ceil(math.log2(E)),
                K_START=math.ceil(3 * NV / 4), PULSE=math.ceil(n / 2) * L,
                TAPS_BITS=int(math.floor(math.log2(T))) + 1, ANT_BITS=math.ceil(math.log2(n)),
                VI_BITS=int(math.floor(math.log2(NV))) + 1)


def m_x_cast(w, p_, d, word):
    out = 0
    flip = 8 // d - 1
    for j in range(8):
        f = (word >> (((j ^ flip)) * w)) & ((1 << w) - 1)
        out |= u(s(f, w), p_) << ((7 - j) * p_)
    return out


def conj_swap(word, w):
    """{c3,c2,c1,c0} -> {conj c3, conj c2, conj c0, conj c1}, W-bit Wrap negate."""
    c = [(word >> (2 * w * i)) & ((1 << 2 * w) - 1) for i in range(4)]
    cj = [((x >> w) << w) | u(-s(x, w), w) for x in c]
    return (cj[3] << 6 * w) | (cj[2] << 4 * w) | (cj[0] << 2 * w) | cj[1]


class NegedgeDelay:
    def __init__(self, L):
        self.L, self.nb = L, math.ceil(math.log2(L + 1))
        self.prev = self.cnt = self.d1 = 0

    def out(self, x):
        return x | self.d1 | int(self.cnt <= self.L - 2)

    def step(self, x):
        ne = int(not x and self.prev)
        run = int(self.cnt <= self.L - 2)
        self.cnt = 0 if ne else ((self.cnt + 1) % (1 << self.nb) if run else self.cnt)
        self.prev = self.d1 = x


def m_write_ctrl(q, sync, data_in, xeng_valid, window_valid):
    """Structural model of write_ctrl. Returns dict of per-cycle outputs."""
    T, N, NV, E, PIV = q["T"], q["N"], q["NV"], q["E"], q["PIVOT"]
    w = q["W"]
    ned = NegedgeDelay(q["PULSE"])
    sync_d = win_prev = valid_in = rst = vld = 0
    dat = [0, 0]
    tap = line = element = 0
    ge = tap0 = 0
    c3, c2 = 0, PIV
    at_k = at_k_prev = 0
    out = dict(start_readout=[], write_addr=[], data_out=[], enable=[])
    for sy, x, xv, wv in zip(sync, data_in, xeng_valid, window_valid):
        rst_in = sync_d | (wv & (1 - win_prev))
        ned_out = ned.out(wv)
        tap_end = int(tap == T - 1)
        last = 1 - ge
        blank = tap0 & last
        out["write_addr"].append(c2 if last else c3)
        out["enable"].append(vld & (1 - blank))
        out["data_out"].append(conj_swap(dat[1], w) if last else dat[1])
        out["start_readout"].append(at_k & (1 - at_k_prev))
        # register updates (all from the values above)
        n_ge = int(tap >= (T - 1) - line)
        n_tap0 = int(tap == 0)
        n_c3 = 0 if rst else ((0 if c3 == PIV - 1 else c3 + 1) if (vld and not last) else c3)
        n_c2 = PIV if rst else ((PIV if c2 == E - 1 else c2 + 1)
                                if (last and not blank and vld) else c2)
        n_tap = 0 if rst_in else ((0 if tap == T - 1 else tap + 1) if (tap_end or valid_in) else tap)
        n_line = 0 if rst_in else ((0 if line == N - 1 else line + 1) if (tap_end and valid_in) else line)
        n_el = 0 if rst_in else ((0 if element == NV - 1 else element + 1) if valid_in else element)
        at_k_prev, at_k = at_k, int(element == q["K_START"])
        ge, tap0, c3, c2 = n_ge, n_tap0, n_c3, n_c2
        tap, line, element = n_tap, n_line, n_el
        vld, rst = valid_in, rst_in
        valid_in = ned_out & xv
        ned.step(wv)
        dat = [x, dat[0]]
        sync_d, win_prev = sy, wv
    return out


def m_read_ctrl(q, start):
    dly = rd = done = 0
    out = dict(read_addr=[], enable=[])
    for st in start:
        pace = int(dly >= q["DEL"])
        en = pace & (1 - done)
        at_end = int(rd >= q["CNT"])
        out["read_addr"].append(rd)
        out["enable"].append(en)
        dly = 0 if (st or pace) else (dly + 1) % (1 << q["DEL_BITS"])
        nrd = 0 if st else ((rd + 1) % (1 << q["RD_BITS"]) if en else rd)
        done = 0 if st else (at_end if at_end else done)
        rd = nrd
    return out


def m_xeng_descramble(q, ram_lat, acc, valid, sync, win_valid, stats=None):
    wc = m_write_ctrl(q, sync, acc, valid, win_valid)
    rc = m_read_ctrl(q, wc["start_readout"])
    d, ow, p_ = q["D"], q["OW"], q["P"]
    mem = [0] * (q["E"] + 1)
    rdata, collisions = 0, 0
    pipe = [0] * (ram_lat - 1)
    subp = [0] * ram_lat
    validp = [0] * ram_lat
    andp = [0] * ram_lat
    seen = 0
    out = dict(acc_out=[], valid_out=[], sync_out=[])
    for i in range(len(acc)):
        rd_out = pipe[-1] if pipe else rdata
        out["acc_out"].append((rd_out >> (subp[-1] * ow)) & ((1 << ow) - 1))
        out["valid_out"].append(validp[-1])
        out["sync_out"].append(andp[-1])
        st = wc["start_readout"][i]
        ra = rc["read_addr"][i]
        new_rdata = mem[(ra // d) % len(mem)] if ra // d < len(mem) else 0
        if wc["enable"][i]:
            if wc["write_addr"][i] == ra // d:
                collisions += 1
            mem[wc["write_addr"][i]] = m_x_cast(q["W"], p_, d, wc["data_out"][i])
        pipe = ([rdata] + pipe[:-1]) if pipe else pipe
        rdata = new_rdata
        subp = [ra % d] + subp[:-1]
        validp = [rc["enable"][i]] + validp[:-1]
        andp = [st & seen] + andp[:-1]
        seen = 0 if st else (1 if sync[i] else seen)
    if stats is not None:
        stats["collisions"] = collisions
        stats["start"] = [i for i, v in enumerate(wc["start_readout"]) if v]
    return out


def element_map(n):
    """Address of each (line, tap) word: the plan's map, from arithmetic only.
    Returns {(line, tap): (addr or None for blank, conjugated)}."""
    T = n // 2 + 1
    piv = n // 2 * T + T * n // 4
    normal, conj, m = 0, piv, {}
    for line in range(n):
        for tap in range(T):
            if line + tap < T - 1:
                if tap == 0:
                    m[(line, tap)] = (None, True)
                else:
                    m[(line, tap)] = (conj, True)
                    conj += 1
            else:
                m[(line, tap)] = (normal, False)
                normal += 1
    return m


PLAN_MAPS = {  # appendix D tables (line: taps 0..T-1; '*' = conjugated, '-' = blank)
    8: ["- 30* 31* 32* 0", "- 33* 34* 1 2", "- 35* 3 4 5", "- 6 7 8 9",
        "10 11 12 13 14", "15 16 17 18 19", "20 21 22 23 24", "25 26 27 28 29"],
    6: ["- 18* 19* 0", "- 20* 1 2", "- 3 4 5", "6 7 8 9", "10 11 12 13", "14 15 16 17"],
    4: ["- 9* 0", "- 1 2", "3 4 5", "6 7 8"],
}


def check_element_maps():
    for n, rows in PLAN_MAPS.items():
        m = element_map(n)
        for line, row in enumerate(rows):
            for tap, cell in enumerate(row.split()):
                want = (None, True) if cell == "-" else (int(cell.rstrip("*")), cell.endswith("*"))
                assert m[(line, tap)] == want, (n, line, tap, m[(line, tap)], want)


def check_descramble(q, ram_lat, frames, times, out, start_cycles):
    """Behavioural check, independent of the counter structure:

    * writes: word i of a frame (line i // T, tap i % T) goes to the address of
      element_map() (blank / conjugated as there) at its arrival cycle + 2;
    * reads: after each start at s, narrow word r (r = 0 .. D*E-1, element
      r // D, block r % D from the MSB of the stored word, fields sign-extended
      to P bits) is read at s+1+r (DEL = 0) or s+1+DEL+r*(DEL+1), and appears
      on acc_out with valid_out = 1 RAM_LATENCY cycles later;
    * a read returns the RAM as left by the writes of earlier cycles.

    Returns, per readout, the elements read from the next output window's
    words. With back-to-back windows these are exactly the conjugated region
    PIVOT..E-1: the X-engine emits the wrapped-around baselines of a data
    frame (its taps' a_end inputs) in the first lines of the following
    window, and the descramble picks them up from there."""
    n, d, w, p_, T = q["N"], q["D"], q["W"], q["P"], q["T"]
    m = element_map(n)
    writes = {}
    i = 0
    for fi, words in enumerate(frames):
        for idx, x in enumerate(words):
            addr, cj = m[(idx // T, idx % T)]
            if addr is not None:
                writes.setdefault(times[i] + 2, []).append((addr, conj_swap(x, w) if cj else x, fi))
            i += 1
    ram, overwritten = {}, []
    wtimes = sorted(writes)
    per = 8 // d
    for fr, st in enumerate(start_cycles):
        rtimes = [st + 1 + r if q["DEL"] == 0 else st + 1 + q["DEL"] + r * (q["DEL"] + 1)
                  for r in range(d * q["E"])]
        src = {}
        for r, rt in enumerate(rtimes):
            for wt in wtimes:
                if wt >= rt:
                    break
                for addr, x, fi in writes[wt]:
                    ram[addr] = (x, fi)
            wtimes = [wt for wt in wtimes if wt >= rt]
            e, k = divmod(r, d)
            x, fi = ram.get(e, (0, -1))
            src[e] = fi
            fields = [s(x >> (w * (7 - f)), w) for f in range(8)]
            word = 0
            for f in fields[k * per:(k + 1) * per]:
                word = (word << p_) | u(f, p_)
            ot = rt + ram_lat
            if ot < len(out["acc_out"]):
                assert (out["acc_out"][ot], out["valid_out"][ot]) == (word, 1), (st, r, ot)
        overwritten.append(sorted(e for e, fi in src.items() if fi > fr))
    return overwritten


def xeng_stream(rng, q, frames, n_ants, acc_len, s0=6, jitter=False, burst_gap=False, neg=True,
                probes=False):
    """X-engine-like input: sync at s0, window_valid rising 2 cycles later and
    high for `frames` frames of N*ACC_LEN cycles. As at the end of the
    X-engine's tap chain, each antenna line (every ACC_LEN cycles) delivers a
    burst of T consecutive valid words. jitter: random 0..2 cycle shift of each
    burst; burst_gap: a 1-cycle hole before the last word of some bursts (the
    tap counter, enabled by (tap == T-1) | valid, then wraps early and the
    element map shifts, as in the diagram). After window_valid falls the
    bursts go on for N/2+1 more lines, as the X-engine keeps emitting the
    wrapped baselines of the last frame: negedge_delay accepts the first N/2
    lines (ceil(N/2)*ACC_LEN cycles) and gates the rest. probes: three single
    valid words around the end of that extension. Returns (acc, valid, sync,
    win, per-frame word lists, the last one partial)."""
    w, T, n = q["W"], q["T"], n_ants
    frame = n * acc_len
    w0 = s0 + 2
    cyc = w0 + (frames + 1) * frame + 2 * acc_len + 40
    acc = [rng.randrange(1 << 8 * w) for _ in range(cyc)]
    acc[0] = 0
    valid = [0] * cyc
    win = [0] * cyc
    for t in range(w0, w0 + frames * frame):
        win[t] = 1
    words, times = [], []
    for f in range(frames + 1):
        fw = []
        for line in range(n if f < frames else n // 2 + 1):
            t = w0 + 3 + f * frame + line * acc_len + (rng.randrange(3) if jitter else 0)
            for k in range(T):
                if burst_gap and line % 3 == 1 and k == T - 1:
                    t += 1
                x = rng.randrange(1 << 8 * w)
                if neg and rng.random() < 0.2:
                    # a most-negative field (its conjugate wraps)
                    j = rng.randrange(8)
                    x = (x & ~(((1 << w) - 1) << (w * j))) | ((1 << (w - 1)) << (w * j))
                acc[t] = x
                valid[t] = 1
                if f < frames or line < n // 2:     # the last tail line is gated off
                    fw.append(x)
                    times.append(t)
                t += 1
        words.append(fw)
    if probes:
        tw = w0 + frames * frame                 # window_valid falls here
        for t in (tw + q["PULSE"] - 2, tw + q["PULSE"] - 1, tw + q["PULSE"]):
            valid[t] = 1
    sync = [int(t == s0) for t in range(cyc)]
    xeng_stream.times = times
    return acc, valid, sync, win, words


def gen_x_cast():
    mdir = TEST_DATA_ROOT / CATEGORY / "Internal" / "x_cast"
    keys = ["N_BITS_IN", "N_BITS_OUT", "FIX_PNT_POS", "DEMUX_FACTOR"]
    specs = [(P(keys, [16, 16, 6, 8]), "W 16 -> P 16, demux 8 (all fields reversed)"),
             (P(keys, [15, 16, 6, 4]), "W 15 -> P 16, demux 4 (pairs reversed)"),
             (P(keys, [25, 32, 14, 2]), "W 25 -> P 32, demux 2 (halves swapped)"),
             (P(keys, [13, 16, 6, 1]), "W 13 -> P 16, demux 1 (order kept)")]
    sets, cycles = [], []
    for k, (p, desc) in enumerate(specs):
        rng = random.Random(f"x_cast-{k}")
        w = p["N_BITS_IN"]
        din = [0] + [rng.randrange(1 << 8 * w) for _ in range(199)]
        din[1] = int("".join("1" + "0" * (w - 1) for _ in range(8)), 2)  # all most-negative
        dout = [m_x_cast(w, p["N_BITS_OUT"], p["DEMUX_FACTOR"], x) for x in din]
        write_set(mdir / f"simdata{k}", p, dict(din=din, dout=dout))
        sets.append((p, desc))
        cycles.append(len(din))
    write_md(mdir, "x_cast",
             "`x_cast` (combinational) reverses the order of the `DEMUX_FACTOR` blocks of "
             "the 8 W-bit fields, keeps the field order inside each block and sign-extends "
             "every field to `N_BITS_OUT` bits. Random words plus one word of 8 "
             "most-negative fields; the first input is 0 (cycle 0 is read at the t = 0 "
             "edge).", sets, cycles)
    return toml_block("Correlator/Internal", "x_cast", sets)


def gen_read_ctrl():
    mdir = TEST_DATA_ROOT / CATEGORY / "Internal" / "read_ctrl"
    keys = ["DEL", "CNT", "DEL_BITS", "RD_BITS"]
    specs = [(P(keys, [2, 288, 2, 9]), "xeng_descramble defaults (N 8, demux 8): one word every 3 cycles"),
             (P(keys, [0, 79, 1, 7]), "DEL 0: back-to-back words, CNT = D*E-1"),
             (P(keys, [84, 10, 7, 4]), "xeng_descramble_4ant defaults: DEL 84, CNT 10"),
             (P(keys, [7, 42, 3, 6]), "DEL 7, CNT 42")]
    sets, cycles = [], []
    for k, (p, desc) in enumerate(specs):
        rng = random.Random(f"read_ctrl-{k}")
        pass_len = (p["DEL"] + 1) * (p["CNT"] + 1)
        cyc = 4 * pass_len + 100
        start = [0] * cyc
        t0 = pass_len + 20                      # after the power-on pass
        for t in (t0, t0 + pass_len + 7, t0 + 2 * pass_len + pass_len // 2):
            start[t] = 1                        # the last one restarts a running pass
        out = m_read_ctrl(dict(p), start)
        write_set(mdir / f"simdata{k}", p, dict(start=start, **out))
        sets.append((p, desc))
        cycles.append(cyc)
    write_md(mdir, "read_ctrl",
             "`read_ctrl` steps the narrow read address 0..CNT one every DEL+1 cycles after "
             "each `start` and stops (done) at CNT. Each set shows the spontaneous power-on "
             "pass (done powers on at 0), two complete passes and a `start` in the middle "
             "of a running pass.", sets, cycles)
    return toml_block("Correlator/Internal", "read_ctrl", sets)


def gen_write_ctrl():
    mdir = TEST_DATA_ROOT / CATEGORY / "Internal" / "write_ctrl"
    keys = ["NUM_ANTS", "ACC_LEN", "W"]
    specs = [((8, 4, 128), "N 8, ACC_LEN 128 (W 16), probe words at the end of the negedge_delay extension", False),
             ((6, 4, 16), "N 6, ACC_LEN 16 (W 13), burst start jitter", True),
             ((4, 8, 64), "N 4, ACC_LEN 64 (W 23): the 4ant map, Counter2 constant 9", False),
             ((10, 4, 8), "N 10, ACC_LEN 8 (W 12), a hole before the last word of some bursts", "gap")]
    sets, cycles = [], []
    for k, ((n, nb, L), desc, jit) in enumerate(specs):
        rng = random.Random(f"write_ctrl-{k}")
        q = desc_params(n, nb, L, 1)
        p = P(keys, [n, L, q["W"]])
        acc, valid, sync, win, _ = xeng_stream(rng, q, 2, n, L, jitter=(jit is True),
                                               burst_gap=(jit == "gap"), probes=(k == 0))
        out = m_write_ctrl(q, sync, acc, valid, win)
        write_set(mdir / f"simdata{k}", p, dict(sync=sync, data_in=acc, xeng_valid=valid,
                                                window_valid=win, **out))
        sets.append((p, desc))
        cycles.append(len(acc))
    write_md(mdir, "write_ctrl",
             "`write_ctrl` turns the X-engine's tap-ordered words into RAM writes: address "
             "(normal region from 0, conjugated last-triangle words from PIVOT, the "
             "redundant tap-0 words blanked), write enable, the possibly conjugated data "
             "word and start_readout. Stimulus: sync, a window of two frames with NV valid "
             "words each (random, some most-negative fields), junk data between valid "
             "words. As at the end of the X-engine's tap chain, every antenna line is a "
             "burst of T consecutive valid words; after window_valid falls the bursts go on "
             "for N/2+1 lines (negedge_delay accepts N/2 of them).", sets, cycles)
    return toml_block("Correlator/Internal", "write_ctrl", sets)


def gen_descramble_sets(mdir, specs, ram_lat, keys, fixed_n=None):
    sets, cycles = [], []
    for k, (args, desc, check, jit) in enumerate(specs):
        n = fixed_n or args[0]
        nb, L, d = args[-3:]
        rng = random.Random(f"{mdir.name}-{k}")
        q = desc_params(n, nb, L, d)
        p = dict(zip(keys, (args if fixed_n is None else args)))
        if fixed_n is None:
            p["RAM_LATENCY"] = ram_lat
        # start after the power-on read pass: a read of the word being written
        # (cross-port collision) is undefined for the RAM
        s0 = (q["CNT"] + 1) * (q["DEL"] + 1) + 10
        acc, valid, sync, win, frames = xeng_stream(rng, q, 3, n, L, s0=s0, jitter=(jit is True),
                                                    burst_gap=(jit == "gap"))
        st = {}
        out = m_xeng_descramble(q, ram_lat, acc, valid, sync, win, st)
        if check:
            assert st["collisions"] == 0, (desc, st["collisions"])
            st["overwritten"] = check_descramble(q, ram_lat, frames, xeng_stream.times, out,
                                                 st["start"])
            print(f"# {mdir.name} set {k}: elements taken from the next output window, "
                  f"per readout: {st['overwritten']}", file=sys.stderr)
        # the power-on pass is visible: D*E valid words before the first start
        assert sum(out["valid_out"][:st["start"][0]]) == q["D"] * q["E"], desc
        write_set(mdir / f"simdata{k}", p, dict(acc=acc, valid=valid, sync=sync,
                                                win_valid=win, **out))
        sets.append((p, desc))
        cycles.append(len(acc))
    return sets, cycles


def gen_xeng_descramble():
    check_element_maps()
    mdir = TEST_DATA_ROOT / CATEGORY / "xeng_descramble"
    keys = ["NUM_ANTS", "N_BITS", "ACC_LEN", "DEMUX_FACTOR"]
    specs = [((8, 4, 128, 8), "Mask defaults: N 8, demux 8 (W 16, DEL 2, CNT 288)", True, False),
             ((6, 4, 64, 2), "N 6, demux 2 (W 15 -> P 16, DEL 7)", True, False),
             ((4, 8, 32, 4), "N 4, demux 4 (W 22 -> P 32, DEL 1)", True, True),
             ((10, 4, 16, 1), "N 10, demux 1 (W 13, DEL 1), burst start jitter", True, True),
             ((8, 4, 128, 4), "A hole before the last word of some bursts: the tap counter wraps early (map shifts, as in the diagram)", False, "gap"),
             ((8, 4, 8, 8), "ship_el_del < 0 (mask errordlg, uses 0): readout overruns the frame", False, False)]
    sets, cycles = gen_descramble_sets(mdir, specs, 1, keys)
    write_md(mdir, "xeng_descramble",
             "`xeng_descramble` writes the X-engine's tap-ordered words to a RAM in element "
             "order (conjugating and swapping the last-triangle words) and reads every "
             "element out as `DEMUX_FACTOR` narrow words after `start_readout`. Stimulus: "
             "sync, three frames of NV valid words. For all but the last set the generator "
             "checks every readout against the element table computed from (line, tap) "
             "arithmetic (the appendix D map, itself checked against the plan's tables for "
             "N = 4, 6, 8), and that reads never hit the wide word being written. Every set "
             "shows the spontaneous power-on read pass (D*E valid words, RAM powers up to 0, "
             "no sync_out).", sets, cycles)
    return toml_block(CATEGORY, "xeng_descramble", sets)


def gen_xeng_descramble_4ant():
    mdir = TEST_DATA_ROOT / CATEGORY / "xeng_descramble_4ant"
    keys = ["N_BITS", "ACC_LEN", "DEMUX_FACTOR"]
    specs = [((8, 256, 1), "Mask defaults: W 25 -> P 32, OW 256, DEL 84, CNT 10", True, False),
             ((4, 16, 2), "4-bit, ACC_LEN 16, demux 2", True, True),
             ((8, 64, 4), "8-bit, ACC_LEN 64, demux 4", True, False)]
    sets, cycles = gen_descramble_sets(mdir, specs, 2, keys, fixed_n=4)
    write_md(mdir, "xeng_descramble_4ant",
             "`xeng_descramble_4ant` is `xeng_descramble` with 4 antennas and a read side "
             "of latency 2 (RAM, valid_out, sync_out). Stimulus and checks as for "
             "`xeng_descramble`.", sets, cycles)
    return toml_block(CATEGORY, "xeng_descramble_4ant", sets)


# ── xeng ─────────────────────────────────────────────────────────────────────
def xeng_derived(p):
    n, nb, L = p["N_ANTS"], p["N_BITS"], p["ACC_LEN"]
    m = 2 * nb + 1 + math.ceil(math.log2(L))
    q = desc_params(n, nb, L, p["DEMUX_FACTOR"])
    xd = p["ADD_LATENCY"] + p["MULT_LATENCY"] + L + math.floor(n / 2 + 1) + 1
    return m, q, xd


def m_xeng(p, sync_in, ant, window_valid, mcnt_in, stats=None):
    from gen_hold_window_test_data import m_window_delay, m_sample_and_hold
    n, L = p["N_ANTS"], p["ACC_LEN"]
    m, q, xd = xeng_derived(p)
    taps = m_tap_chain(n, L, ant, sync_in, bits=p["N_BITS"], mult=p["MULT_LATENCY"],
                       add=p["ADD_LATENCY"])
    assert taps[0]["a_end_out"] == delayed(ant, n * L), "a_end_out lag != N_ANTS*ACC_LEN"
    last = taps[-1]
    acc_d = [x & ((1 << 8 * q["W"]) - 1) for x in last["acc_out"]]
    win = m_window_delay(dict(DELAY=xd), window_valid)
    st = {} if stats is None else stats
    d_out = m_xeng_descramble(q, 2 if n == 4 else 1, acc_d, last["valid_out"],
                              last["sync_out"], win, st)
    per = n * L
    sah1 = m_sample_and_hold(dict(PERIOD=per), sync_in, mcnt_in)
    sah2 = m_sample_and_hold(dict(PERIOD=per), last["sync_out"], sah1)
    sah3 = m_sample_and_hold(dict(PERIOD=per), d_out["sync_out"], sah2)
    return dict(sync_out=d_out["sync_out"], acc=d_out["acc_out"], valid=d_out["valid_out"],
                mcnt_out=delayed(sah3, 1))


def check_xeng(p, ant, t0, out, starts):
    """End-to-end check: every complete readout is the E dual-polarisation
    visibilities of one data frame, one per baseline. Data frame f, antenna
    j, sample s is at cycle t0 + (f*N + j)*ACC_LEN + s (t0 = sync + 1).
    Returns [(frame, [(x, y) per element address])] for the checked readouts."""
    n, nb, L = p["N_ANTS"], p["N_BITS"], p["ACC_LEN"]
    _, q, _ = xeng_derived(p)
    d, P_, E = q["D"], q["P"], q["E"]
    per = 8 // d

    def pols(t):
        x = ant[t]
        xr, xi, yr, yi = unpack(x, nb, 4)
        return complex(xr, xi), complex(yr, yi)

    def vis(f, a, b):
        acc = [0j] * 4
        for s_ in range(L):
            ta = t0 + (f * n + a) * L + s_
            tb = t0 + (f * n + b) * L + s_
            ax, ay = pols(ta)
            bx, by = pols(tb)
            for i, (u_, v_) in enumerate([(ax, bx), (ay, by), (ax, by), (ay, bx)]):
                acc[i] += u_ * v_.conjugate()
        return tuple(int(c) for z in acc for c in (z.real, z.imag))

    nframes = (len(ant) - t0) // (n * L)
    table = {}
    for f in range(nframes):
        for a in range(n):
            for b in range(n):
                table.setdefault(vis(f, a, b), []).append((f, a, b))
    results = []
    for st in starts:
        words = [o for t, (o, v) in enumerate(zip(out["acc"], out["valid"])) if v and t > st]
        if len(words) < d * E:
            continue
        found = []
        for e in range(E):
            fields = []
            for k in range(d):
                w_ = words[e * d + k]
                fields += [s(w_ >> (P_ * (per - 1 - j)), P_) for j in range(per)]
            hits = table.get(tuple(fields))
            if not hits:
                found = None
                break
            found.append(hits)
        if found is None:
            continue
        frames = {h[0] for hits in found for h in hits}
        for f in sorted(frames):
            pairs = [next(((a, b) for (ff, a, b) in hits if ff == f), None) for hits in found]
            if None not in pairs and {tuple(sorted(x)) for x in pairs} == {
                    (x, y) for x in range(n) for y in range(x, n)}:
                results.append((f, pairs))
                break
    return results



XENG_KEYS = ["N_ANTS", "N_BITS", "ACC_LEN", "DEMUX_FACTOR", "ADD_LATENCY", "MULT_LATENCY",
             "BRAM_LATENCY", "USE_DED_MULT", "USE_BRAM_DELAY", "MCNT_BITS"]


def gen_xeng():
    mdir = TEST_DATA_ROOT / CATEGORY / "xeng"
    # (params, description, e2e check, extra syncs, window high from power-on)
    specs = [
        (P(XENG_KEYS, [8, 4, 128, 4, 1, 1, 2, 1, 1, 16]),
         "Mask defaults (N_ANTS 8 from xeng_init.m), periodic sync", True, True, False),
        (P(XENG_KEYS, [4, 4, 16, 2, 1, 1, 2, 1, 0, 8]),
         "4 antennas: xeng_descramble_4ant, delay_slr", True, False, False),
        (P(XENG_KEYS, [6, 4, 8, 1, 0, 2, 2, 1, 1, 8]),
         "6 antennas, ACC_LEN 8, add latency 0", True, False, False),
        (P(XENG_KEYS, [10, 3, 16, 1, 1, 1, 1, 1, 1, 8]),
         "10 antennas, 3-bit samples", True, False, False),
        (P(XENG_KEYS, [8, 4, 12, 1, 1, 1, 2, 1, 1, 8]),
         "ACC_LEN 12 (not a power of 2): W = N_BITS_OUT-1, descramble fields misaligned ($warning)", False, False, False),
        (P(XENG_KEYS, [8, 4, 32, 4, 1, 1, 2, 1, 1, 8]),
         "Read pace 1.6 rounded to DEL 0: the last conjugated element is read before the next window rewrites it", "mixed", False, False),
        (P(XENG_KEYS, [4, 4, 8, 1, 1, 1, 2, 1, 1, 8]),
         "window_valid high from power-on (window_delay rises at XENG_DELAY), sync later", False, False, True),
    ]
    sets, cycles = [], []
    for k, (p, desc, check, extra_sync, win_poweron) in enumerate(specs):
        rng = random.Random(f"xeng-{k}")
        n, nb, L = p["N_ANTS"], p["N_BITS"], p["ACC_LEN"]
        m, q, xd = xeng_derived(p)
        frame = n * L
        s0 = (q["CNT"] + 1) * (q["DEL"] + 1) + 10      # after the power-on read pass
        F = 3
        cyc = s0 + 1 + (F + 2) * frame + (q["CNT"] + 1) * (q["DEL"] + 1) + 60
        ant = [0] * cyc
        for t in range(s0 + 1, s0 + 1 + F * frame):
            ant[t] = rng.randrange(1 << 4 * nb)
        # one frame of most-negative samples (maximum growth)
        neg = pack([-(1 << (nb - 1))] * 4, nb)
        for t in range(s0 + 1 + frame, s0 + 1 + frame + L):
            ant[t] = neg
        syncs = [s0] + ([s0 + 2 * frame] if extra_sync else [])
        sync = [int(t in syncs) for t in range(cyc)]
        win = [int((win_poweron and t < s0 + F * frame) or s0 <= t < s0 + F * frame)
               for t in range(cyc)]
        mcnt = [u(t // 5, p["MCNT_BITS"]) for t in range(cyc)]
        mcnt[0] = 0
        st = {}
        out = m_xeng(p, sync, ant, win, mcnt, st)
        if check == "mixed":
            assert len(check_xeng(p, ant, s0 + 1, out, st["start"])) == 0, desc
        elif check:
            res = check_xeng(p, ant, s0 + 1, out, st["start"])
            assert [f for f, _ in res] == list(range(F)), (desc, [f for f, _ in res])
            print(f"# xeng set {k}: element order {res[0][1]}", file=sys.stderr)
        write_set(mdir / f"simdata{k}", p, dict(sync_in=sync, ant=ant, window_valid=win,
                                                mcnt_in=mcnt, **out))
        sets.append((p, desc))
        cycles.append(cyc)
    write_md(mdir, "xeng",
             "`xeng` chains auto_tap and N_ANTS/2 baseline_taps, closes the antenna loop, "
             "delays window_valid by XENG_DELAY, descrambles the relay stream "
             "(xeng_descramble_4ant for 4 antennas) and carries mcnt through three "
             "sample_and_holds. Stimulus: sync (after the descramble's power-on read pass), "
             "three frames of random antenna data with one most-negative antenna block, a "
             "window over those frames, mcnt = cycle/5. The generator asserts that the "
             "auto_tap's a_end_out lags `ant` by exactly N_ANTS*ACC_LEN (the testbench "
             "checks the same on the RTL), and for the sets marked e2e that every readout "
             "is the E dual-polarisation visibilities "
             "`[XX, YY, XY, YX] = Σ x·conj(y)` of one complete data frame, one per baseline "
             "(x ≤ y), covering every baseline. Set 5 documents the one configuration "
             "family found where that does not hold (read pace 1.6 rounded to DEL 0).",
             sets, cycles)
    return toml_block(CATEGORY, "xeng", sets)



# ── cross_multiplier ─────────────────────────────────────────────────────────
CM_KEYS = ["STREAMS", "AGGREGATION", "BIT_WIDTH_IN", "BIN_PT_IN", "BIT_WIDTH_OUT",
           "BIN_PT_OUT", "MULT_LATENCY", "ADD_LATENCY", "OVERFLOW", "QUANTIZATION", "CONV_LATENCY"]


def m_cross_multiplier(p, sync, din):
    """din: per cycle a list of STREAMS raw words. Returns (sync_out, dout list
    of NOUT raw words per cycle)."""
    from fractions import Fraction
    from gen_fixed_point_test_data import quantize
    S_, A, w, bp = p["STREAMS"], p["AGGREGATION"], p["BIT_WIDTH_IN"], p["BIN_PT_IN"]
    wo, bpo = p["BIT_WIDTH_OUT"], p["BIN_PT_OUT"]
    lat = 1 + p["MULT_LATENCY"] + p["ADD_LATENCY"] + p["CONV_LATENCY"]
    ovf = 1 if p["OVERFLOW"] == 1 else 0
    scale = Fraction(1, 1 << (2 * bp))
    res = []
    for words in din:
        outs = []
        for x in range(S_):
            for y in range(x, S_):
                word = 0
                for sub in range(A):
                    xr, xi = unpack(words[x] >> (2 * w * (A - 1 - sub)), w, 2)
                    yr, yi = unpack(words[y] >> (2 * w * (A - 1 - sub)), w, 2)
                    re = (xr * yr + xi * yi) * scale
                    im = (xi * yr - xr * yi) * scale
                    q = (wo, bpo, 1, p["QUANTIZATION"], ovf)
                    word = (word << 2 * wo) | (quantize(re, *q) << wo) | quantize(im, *q)
                outs.append(word)
        res.append(outs)
    zero = [0] * len(res[0])
    return delayed(sync, lat), [zero] * lat + res[:len(res) - lat]


def gen_cross_multiplier():
    import numpy as np
    mdir = TEST_DATA_ROOT / CATEGORY / "cross_multiplier"
    specs = [
        (P(CM_KEYS, [2, 2, 4, 3, 9, 6, 2, 1, 0, 0, 0]),
         "Stored mask values with STREAMS 2: Fix_4_3 -> Fix_9_6 is lossless"),
        (P(CM_KEYS, [4, 1, 8, 7, 12, 9, 1, 1, 1, 1, 1]),
         "4 streams, 8-bit, round half away from zero + saturate, convert latency 1"),
        (P(CM_KEYS, [3, 4, 4, 3, 6, 4, 1, 0, 2, 2, 2]),
         "3 streams x 4 sub-streams, round half to even, overflow Error (= wrap), add latency 0"),
        (P(CM_KEYS, [1, 2, 6, 5, 13, 10, 3, 2, 0, 0, 0]),
         "1 stream: autocorrelations only (imaginary parts 0)"),
    ]
    sets, cycles = [], []
    for k, (p, desc) in enumerate(specs):
        rng = random.Random(f"cross_multiplier-{k}")
        S_, A, w = p["STREAMS"], p["AGGREGATION"], p["BIT_WIDTH_IN"]
        cyc = 300
        din = []
        for t in range(cyc):
            words = []
            for x in range(S_):
                if t == 0:
                    words.append(0)
                elif t < 12:
                    # corner cases: all parts most negative / most positive / mixed
                    v = [-(1 << (w - 1)), (1 << (w - 1)) - 1][(t + x) % 2]
                    words.append(pack([v if (j + t) % 3 else -v - 1 for j in range(2 * A)], w))
                else:
                    words.append(rng.randrange(1 << 2 * A * w))
            din.append(words)
        sync = [int(t in (5, 150)) for t in range(cyc)]
        sync_out, dout = m_cross_multiplier(p, sync, din)
        lat = 1 + p["MULT_LATENCY"] + p["ADD_LATENCY"] + p["CONV_LATENCY"]
        if k == 0:  # lossless: compare with numpy x * conj(y)
            for t in range(lat, cyc):
                kk = 0
                for x in range(S_):
                    for y in range(x, S_):
                        for sub in range(A):
                            xr, xi = unpack(din[t - lat][x] >> (2 * w * (A - 1 - sub)), w, 2)
                            yr, yi = unpack(din[t - lat][y] >> (2 * w * (A - 1 - sub)), w, 2)
                            z = np.complex128(complex(xr, xi)) * np.conj(complex(yr, yi))
                            o_re, o_im = unpack(dout[t][kk] >> (2 * 9 * (A - 1 - sub)), 9, 2)
                            assert (o_re, o_im) == (int(z.real), int(z.imag)), (t, x, y, sub)
                        kk += 1
        if S_ == 1:
            for t in range(cyc):
                for sub in range(A):
                    assert unpack(dout[t][0] >> (2 * 13 * (A - 1 - sub)), 13, 2)[1] == 0
        write_set(mdir / f"simdata{k}", p, dict(sync_in=sync, din=din, sync_out=sync_out,
                                                dout=[list(o) for o in dout]))
        sets.append((p, desc))
        cycles.append(cyc)
    write_md(mdir, "cross_multiplier",
             "`cross_multiplier` computes `din[x] · conj(din[y])` for every pair x ≤ y and "
             "every sub-stream (full precision, then convert_of to the output format), "
             "latency `1 + MULT + ADD + CONV`. `din` / `dout` are packed arrays with one "
             "file per element: `sim_din<x>.csv` is stream x (`din[x]`), `sim_dout<k>.csv` "
             "output k (pairs in x, y order); inside a word sub-stream 0 is in the MSBs and each "
             "complex value is {re, im}. The first cycles walk most-negative / "
             "most-positive parts, the rest is random. Set 0 is checked against numpy "
             "`x * conj(y)`, set 3 (autocorrelations) for zero imaginary parts.",
             sets, cycles)
    return toml_block(CATEGORY, "cross_multiplier", sets)



# ── xeng_tvg ─────────────────────────────────────────────────────────────────
TVG_CONST = 0x1A4E   # {0.1 -> 0.125, -0.75, 0.5, -0.25} as Fix_4_3


def m_xeng_tvg(p, tvg_sel, sync, data_in, valid_in, tv):
    X, SP = p["X_INT_BITS"], p["SYNC_PERIOD"]
    rel = use = sel_d = 0
    cnt4, e2_prev = (1 << SP) - 2, 0
    cnt, ant_prev, rst_d = 0, 0, 0
    c1, c2, c3 = 0, 0, 15
    dpipe, concat1_d, mux2, mux3 = [0, 0], 0, 0, 0
    vpipe, spipe = [0, 0, 0], [0, 0]
    out = dict(sync_out=[], data_out=[], valid_out=[])
    for ts, sy, di, vi in zip(tvg_sel, sync, data_in, valid_in):
        msb4 = (cnt4 >> SP) & 1
        edge2 = msb4 ^ e2_prev
        sync_int = edge2 if use else sy
        msbc = (cnt >> X) & 1
        ant_en = msbc ^ ant_prev
        out["data_out"].append(mux3)
        out["valid_out"].append(vpipe[2])
        out["sync_out"].append(spipe[1])
        mux3 = [dpipe[1], concat1_d, TVG_CONST, mux2][sel_d]
        mux2 = tv[c2] & 0xFFFF
        concat1_d = (c1 << 12) | (c3 << 8) | (c1 << 4) | c3
        dpipe = [di, dpipe[0]]
        if rst_d:
            c1, c2, c3 = 0, 0, 15
        elif ant_en:
            c1, c2, c3 = (c1 + 1) % 16, (c2 + 1) % 8, (c3 - 1) % 16
        vpipe = [1 if use else vi, vpipe[0], vpipe[1]]
        spipe = [rst_d, spipe[0]]
        rst_d = sync_int
        cnt = 0 if sync_int else (cnt + 1) % (1 << (X + 1))
        ant_prev, e2_prev = msbc, msb4
        cnt4 = (cnt4 + 1) % (1 << (SP + 1))
        use, rel, sel_d = rel, int(ts != 0), ts
    return out


def gen_xeng_tvg():
    mdir = TEST_DATA_ROOT / CATEGORY / "xeng_tvg"
    keys = ["ANT_BITS", "X_INT_BITS", "SYNC_PERIOD", "DATA_WIDTH"]
    specs = [(P(keys, [2, 5, 15, 16]), "Mask defaults (internal sync period 2^15: one pulse at t = 2)"),
             (P(keys, [2, 2, 6, 16]), "X_INT_BITS 2, SYNC_PERIOD 6: several internal syncs per mode"),
             (P(keys, [4, 3, 8, 24]), "24-bit data_in (data_out 24 bits)"),
             (P(keys, [2, 1, 1, 8]), "Smallest periods, 8-bit data_in (data_out 16 bits)")]
    sets, cycles = [], []
    for k, (p, desc) in enumerate(specs):
        rng = random.Random(f"xeng_tvg-{k}")
        cyc = 1600
        X = p["X_INT_BITS"]
        # mode schedule: 0 (external sync / data), 1, 2, 3, 0, 3 with sync pulses
        sched = [0] * 200 + [1] * 400 + [2] * 150 + [3] * 450 + [0] * 150 + [3] * 250
        tvg_sel = sched[:cyc]
        tvg_sel[0] = 0
        sync = [int(t in (20, 90, 700, 1320)) for t in range(cyc)]
        data_in = [0] + [rng.randrange(1 << p["DATA_WIDTH"]) for _ in range(cyc - 1)]
        valid_in = [0] + [rng.randrange(2) for _ in range(cyc - 1)]
        tv = [(rng.randrange(1 << 16) << 16) | (0x1111 * j) for j in range(8)]
        out = m_xeng_tvg(p, tvg_sel, sync, data_in, valid_in, tv)
        # behavioural checks
        if k == 1:
            # mode 1: after an internal sync at t0 (sync_out at t0+3), data_out(t0+4)
            # is antenna 0 = {0, 15, 0, 15}, then a new antenna every 2^X cycles
            so = [t for t, v in enumerate(out["sync_out"]) if v and 210 < t < 590]
            assert so, "no internal sync in mode 1"
            t0 = so[0] - 3
            for a in range(4):
                c = a % 16
                assert out["data_out"][t0 + 4 + a * (1 << X)] == (c << 12) | ((15 - c) << 8) | (c << 4) | (15 - c)
            so3 = [t for t, v in enumerate(out["sync_out"]) if v and 760 < t < 1190]
            t0 = so3[0] - 3
            for a in range(9):
                assert out["data_out"][t0 + 4 + a * (1 << X)] == 0x1111 * (a % 8)
        assert TVG_CONST in out["data_out"][610:740]
        write_set(mdir / f"simdata{k}", p, dict(tvg_sel=tvg_sel, sync=sync, data_in=data_in,
                                                valid_in=valid_in, tv=[list(tv)] * cyc, **out))
        sets.append((p, desc))
        cycles.append(cyc)
    write_md(mdir, "xeng_tvg",
             "`xeng_tvg` selects the X-engine input: 0 pass-through, 1 antenna counter "
             "pattern {c, ~c, c, ~c}, 2 the constant 0x1A4E, 3 tv[k][15:0] per antenna. "
             "Stimulus: the mode sequence 0, 1, 2, 3, 0, 3 with external sync pulses, "
             "random data / valid, tv[k] = (random << 16) | 0x1111*k (only the low 16 bits "
             "may appear). `tv` has one file per register: `sim_tv<k>.csv` is tv[k]. Set 1 checks the mode-1 and mode-3 antenna sequences after an "
             "internal sync (antenna 0 at sync_out + 1, then every 2^X_INT_BITS cycles).",
             sets, cycles)
    return toml_block(CATEGORY, "xeng_tvg", sets)


if __name__ == "__main__":
    run_cli(__doc__, {"cmac_acc": gen_cmac_acc, "cmac": gen_cmac,
                      "dual_pol_cmac": gen_dual_pol_cmac, "auto_tap": gen_auto_tap,
                      "baseline_tap": gen_baseline_tap, "x_cast": gen_x_cast,
                      "read_ctrl": gen_read_ctrl, "write_ctrl": gen_write_ctrl,
                      "xeng_descramble": gen_xeng_descramble,
                      "xeng_descramble_4ant": gen_xeng_descramble_4ant, "xeng": gen_xeng,
                      "cross_multiplier": gen_cross_multiplier, "xeng_tvg": gen_xeng_tvg})
