#!/usr/bin/env python3
"""Generate test data for rtl/Misc/convert_of and rtl/FFTs/butterfly_direct.

Expected outputs come from cycle-accurate Python reference models of the
casper_library behavior (convert_of_init.m, butterfly_direct_init.m), not
from the RTL. butterfly_direct's twiddle stage reuses the reference models
of test_data/scripts/gen_twiddle_test_data.py; its twiddle_general table comes from
rtl/FFTs/Twiddle/scripts/gen_twiddle_coeffs.py.

Writes, per module, test_data/<Category>/<module>/simdataN/{params.json,
sim_<port>.csv[, twiddle.mem]} and test_data.md, and prints the matching
[[simulations]] blocks for tests/simulation.toml. CSV rows are clock cycles;
lane ports have N_INPUTS space-separated columns; values are raw unsigned
bit patterns.

Usage:
  python3 test_data/scripts/gen_butterfly_test_data.py            # both modules
  python3 test_data/scripts/gen_butterfly_test_data.py --module convert_of
"""

import json
import random
import sys
from fractions import Fraction
from pathlib import Path

from common import TEST_DATA_ROOT as TEST_DATA, run_cli           # also puts rtl/.../scripts on sys.path
from gen_fixed_point_test_data import quantize, to_value
from gen_twiddle_coeffs import mem_lines, twiddle_table             # rtl/FFTs/Twiddle/scripts/
import gen_twiddle_test_data as tw

SCRIPT = Path(__file__).name


# ── helpers ─────────────────────────────────────────────────────────────────

def delay(seq, latency, zero):
    """Register delay: cycle t shows seq[t-latency]; earlier cycles power-on 0."""
    return [seq[t - latency] if t >= latency else zero for t in range(len(seq))]


def raw(value, n_bits, bin_pt):
    """Exact value -> n_bits two's-complement bit pattern (must fit exactly)."""
    x = value * 2 ** bin_pt
    assert x.denominator == 1, "value not representable"
    return int(x) % (1 << n_bits)


def of_flag(value, n_in, bp_in, n_out, bp_out):
    """convert_of rule: top wb_lost+1 bits of the input not all equal."""
    wb_lost = (n_in - bp_in) - (n_out - bp_out)
    if wb_lost <= 0:
        return 0
    n_top = min(wb_lost + 1, n_in)
    top = raw(value, n_in, bp_in) >> (n_in - n_top)
    return 0 if top in (0, (1 << n_top) - 1) else 1


def write_csv(path, rows):
    path.write_text("".join(
        (" ".join(str(v) for v in r) if isinstance(r, list) else str(r)) + "\n" for r in rows))


def P(names, values):
    return dict(zip(names, values))


# ── convert_of ──────────────────────────────────────────────────────────────

COF = ["N_BITS_IN", "BIN_PT_IN", "N_BITS_OUT", "BIN_PT_OUT", "QUANTIZATION", "OVERFLOW", "LATENCY"]

CONVERT_OF_TESTS = [
    (P(COF, [16, 8, 8, 4, 0, 0, 0]), "Fix_16_8 → Fix_8_4, truncate + wrap, combinational"),
    (P(COF, [16, 12, 8, 4, 1, 1, 1]), "Fix_16_12 → Fix_8_4, round + saturate"),
    (P(COF, [12, 10, 12, 10, 0, 0, 2]), "same integer bits: overflow impossible, of = 0"),
    (P(COF, [18, 16, 18, 17, 2, 1, 1]), "one integer bit dropped (butterfly-style), round even"),
    (P(COF, [8, 4, 12, 4, 0, 0, 1]), "bit growth: of = 0"),
]


def gen_convert_of():
    name, cycles = "convert_of", 256
    mdir = TEST_DATA / "Misc" / name
    for n, (p, _) in enumerate(CONVERT_OF_TESTS):
        rng = random.Random(f"{name}-{n}")
        w = p["N_BITS_IN"]
        m = 1 << (w - 1)
        din = [0, 1, (1 << w) - 1, m, m - 1, m + 1]
        din += [rng.randrange(1 << w) for _ in range(cycles - len(din))]
        dout, of = [], []
        for x in din:
            v = to_value(x, w, p["BIN_PT_IN"], 1)
            dout.append(quantize(v, p["N_BITS_OUT"], p["BIN_PT_OUT"], 1,
                                 p["QUANTIZATION"], p["OVERFLOW"]))
            of.append(of_flag(v, w, p["BIN_PT_IN"], p["N_BITS_OUT"], p["BIN_PT_OUT"]))
        lat = p["LATENCY"]
        dout, of = delay(dout, lat, 0), delay(of, lat, 0)
        if lat == 0:            # first clock edge is at t = 0, before din arrives
            dout[0] = of[0] = 0
        d = mdir / f"simdata{n}"
        d.mkdir(parents=True, exist_ok=True)
        (d / "params.json").write_text(json.dumps(p, indent=2) + "\n")
        write_csv(d / "sim_din.csv", din)
        write_csv(d / "sim_out.csv", dout)
        write_csv(d / "sim_of.csv", of)
    keys = COF
    lines = [
        f"# {name} test data", "",
        "`convert_of` is `convert` (signed) plus casper_library's overflow flag: "
        "`of` = 1 when the top `wb_lost+1` bits of `din` are not all equal. "
        "The first cycles walk corner words (0, 1, all-ones, MSB only, MSB−1, "
        "MSB+1); the rest are seeded random.", "",
        "Generated by `test_data/scripts/gen_butterfly_test_data.py` (Python reference "
        "model, not exported from MATLAB). Files: `sim_din.csv`, expected "
        "`sim_out.csv` (dout) and `sim_of.csv`, one raw unsigned value per cycle.", "",
        "| Test # | Directory | " + " | ".join(keys) + " | Cycles | Description |",
        "|" + "---|" * (len(keys) + 4),
    ]
    for n, (p, desc) in enumerate(CONVERT_OF_TESTS):
        lines.append(f"| {n} | `simdata{n}` | " + " | ".join(str(p[k]) for k in keys)
                     + f" | {cycles} | {desc} |")
    (mdir / "test_data.md").write_text("\n".join(lines) + "\n")
    return toml("Misc", name, [(p, desc) for p, desc in CONVERT_OF_TESTS], SCRIPT)


# ── butterfly_direct ────────────────────────────────────────────────────────

BF = ["N_INPUTS", "BIPLEX", "FFT_SIZE", "N_COEFFS", "COEFF_0", "COEFF_1", "STEP_PERIOD",
      "COEFF_BIT_WIDTH", "INPUT_BIT_WIDTH", "BIN_PT_IN", "BITGROWTH", "DOWNSHIFT",
      "HARDCODE_SHIFTS", "ADD_LATENCY", "MULT_LATENCY", "BRAM_LATENCY", "CONV_LATENCY",
      "QUANTIZATION", "OVERFLOW", "MAX_FANOUT"]

# BIPLEX, FFT_SIZE, Coeffs, STEP_PERIOD are casper's; the rest of BF follows
BUTTERFLY_TESTS = [
    (1, 1, 5, [0], 4, [18, 18, 17, 0, 0, 0, 1, 2, 1, 1, 1, 0, 4], 256,
     "pass_through (biplex stage 1), dynamic shift, round + wrap"),
    (2, 0, 5, [0], 4, [18, 12, 11, 0, 1, 1, 1, 2, 1, 1, 0, 1, 4], 256,
     "coeff_0 (non-biplex), 2 lanes, hardcoded downshift, truncate + saturate"),
    (1, 0, 5, [1], 4, [18, 16, 15, 0, 0, 0, 2, 1, 1, 2, 2, 1, 1], 256,
     "coeff_1, dynamic shift with MAX_FANOUT 1 (shift latency 2), round even + saturate"),
    (1, 1, 4, [0, 1], 2, [18, 18, 17, 0, 0, 0, 1, 2, 1, 1, 1, 0, 4], 256,
     "stage_2 (biplex stage 2 of a 16-point FFT), dynamic shift"),
    (1, 1, 4, [0, 1, 2, 3], 1, [18, 18, 17, 0, 0, 0, 1, 2, 1, 1, 1, 1, 4], 512,
     "general (stage 3 of 16-point: Coeffs 0..3, StepPeriod 1), round + saturate"),
    (2, 1, 5, list(range(8)), 1, [16, 14, 13, 1, 0, 0, 1, 1, 1, 0, 2, 0, 4], 512,
     "general, 2 lanes, bit growth (15-bit outputs), round even + wrap"),
    (3, 1, 4, [0, 1, 2, 3], 0, [12, 10, 9, 0, 0, 1, 0, 0, 1, 0, 0, 0, 4], 256,
     "general, 3 lanes, hardcoded no shift, truncate + wrap (frequent overflow), minimal latency"),
    (1, 1, 3, [0], 2, [18, 8, 7, 1, 0, 0, 0, 2, 1, 0, 0, 0, 4], 256,
     "pass_through with bit growth and no latency: fully combinational data path"),
]

MEM_REL = "../../../test_data/FFTs/butterfly_direct/simdata{n}/twiddle.mem"
LANE_IN = ["a_re", "a_im", "b_re", "b_im"]
LANE_OUT = ["apbw_re", "apbw_im", "ambw_re", "ambw_im"]


def twiddle_type(p):
    if p["N_COEFFS"] == 1 and p["COEFF_0"] == 0:
        return "pass_through" if p["BIPLEX"] else "coeff_0"
    if p["N_COEFFS"] == 1 and p["COEFF_0"] == 1:
        return "coeff_1"
    if (p["N_COEFFS"] == 2 and p["COEFF_0"] == 0 and p["COEFF_1"] == 1
            and p["STEP_PERIOD"] == p["FFT_SIZE"] - 2):
        return "stage_2"
    return "general"


def run_twiddle(p, coeffs, st):
    """Twiddle outputs as time series (no cycle-0 adjustment)."""
    kind = twiddle_type(p)
    common = {k: p[k] for k in ["N_INPUTS", "INPUT_BIT_WIDTH", "BIN_PT_IN", "MULT_LATENCY",
                                 "ADD_LATENCY", "BRAM_LATENCY", "CONV_LATENCY"]}
    tst = {"ai_re": st["a_re"], "ai_im": st["a_im"], "bi_re": st["b_re"],
           "bi_im": st["b_im"], "sync_in": st["sync_in"]}
    if kind == "pass_through":
        # identity; not tw.m_twiddle_pass_through, whose cycle-0 rule only
        # applies at a module output, not inside the registered adders
        out = {"ao_re": tst["ai_re"], "ao_im": tst["ai_im"], "bwo_re": tst["bi_re"],
               "bwo_im": tst["bi_im"], "sync_out": tst["sync_in"]}
        bw_width = p["INPUT_BIT_WIDTH"]
    elif kind == "coeff_0":
        out, bw_width = tw.m_twiddle_coeff_0(common, tst), p["INPUT_BIT_WIDTH"]
    elif kind == "coeff_1":
        out, bw_width = tw.m_twiddle_coeff_1(common, tst), p["INPUT_BIT_WIDTH"]
    elif kind == "stage_2":
        out = tw.m_twiddle_stage_2(dict(common, FFT_SIZE=p["FFT_SIZE"]), tst)
        bw_width = p["INPUT_BIT_WIDTH"]
    else:
        # single coefficient: casper's constant coeff_gen, read latency 1
        if p["N_COEFFS"] == 1:
            common = dict(common, BRAM_LATENCY=1)
        gp = dict(common, N_COEFFS=p["N_COEFFS"], STEP_PERIOD=p["STEP_PERIOD"],
                  COEFF_BIT_WIDTH=p["COEFF_BIT_WIDTH"], QUANTIZATION=p["QUANTIZATION"],
                  OVERFLOW=p["OVERFLOW"])
        table = twiddle_table(coeffs, p["FFT_SIZE"], p["COEFF_BIT_WIDTH"])
        out, bw_width = tw.m_twiddle_general(gp, tst, table), p["INPUT_BIT_WIDTH"] + 1
    return out, bw_width


def m_butterfly(p, coeffs, st):
    n, iw, bp = p["N_INPUTS"], p["INPUT_BIT_WIDTH"], p["BIN_PT_IN"]
    cycles = len(st["sync_in"])
    twd, bw_w = run_twiddle(p, coeffs, st)
    dynamic = p["BITGROWTH"] == 0 and p["HARDCODE_SHIFTS"] == 0
    mux_lat = 1 if dynamic else 0
    n_out = iw + 1 if p["BITGROWTH"] else iw
    sum_w = bw_w + 1
    conv_in_w = sum_w + 1 if dynamic else sum_w
    conv_in_bp = bp + 1 if (dynamic or (p["HARDCODE_SHIFTS"] and p["DOWNSHIFT"]
                                        and not p["BITGROWTH"])) else bp
    ratio = -(-(n * 4) // p["MAX_FANOUT"])
    fan = max(1, (ratio - 1).bit_length())
    shift_d = delay(st["shift"], fan, 0)

    # exact sums per cycle: comps[t][lane] = [apbw.re, apbw.im, ambw.re, ambw.im]
    comps = []
    for t in range(cycles):
        row = []
        for k in range(n):
            a_re = to_value(twd["ao_re"][t][k], iw, bp, 1)
            a_im = to_value(twd["ao_im"][t][k], iw, bp, 1)
            b_re = to_value(twd["bwo_re"][t][k], bw_w, bp, 1)
            b_im = to_value(twd["bwo_im"][t][k], bw_w, bp, 1)
            row.append([a_re + b_re, a_im + b_im, a_re - b_re, a_im - b_im])
        comps.append(row)
    zero_row = [[Fraction(0)] * 4 for _ in range(n)]
    sums = delay(comps, p["ADD_LATENCY"], zero_row)

    # shift stage: value presented to convert_of
    if dynamic:
        sel = [[[v / 2 if shift_d[t] else v for v in lane] for lane in sums[t]]
               for t in range(cycles)]
        cin = delay(sel, mux_lat, zero_row)
    elif p["HARDCODE_SHIFTS"] and p["DOWNSHIFT"] and not p["BITGROWTH"]:
        cin = [[[v / 2 for v in lane] for lane in sums[t]] for t in range(cycles)]
    else:
        cin = sums

    outs = [[[quantize(v, n_out, bp, 1, p["QUANTIZATION"], p["OVERFLOW"]) for v in lane]
             for lane in cin[t]] for t in range(cycles)]
    flags = [[max(of_flag(v, conv_in_w, conv_in_bp, n_out, bp) for v in lane)
              for lane in cin[t]] for t in range(cycles)]
    outs = delay(outs, p["CONV_LATENCY"], [[0] * 4 for _ in range(n)])
    flags = delay(delay(flags, p["CONV_LATENCY"], [0] * n), 1, [0] * n)
    sync_out = delay(twd["sync_out"], p["ADD_LATENCY"] + mux_lat + p["CONV_LATENCY"], 0)

    tw_lat = {"pass_through": 0,
              "coeff_0": 1 + p["MULT_LATENCY"] + p["ADD_LATENCY"] + p["CONV_LATENCY"],
              "coeff_1": 1 + p["MULT_LATENCY"] + p["ADD_LATENCY"] + p["CONV_LATENCY"]}.get(
        twiddle_type(p),
        (1 if p["N_COEFFS"] == 1 else p["BRAM_LATENCY"]) + p["MULT_LATENCY"] + p["ADD_LATENCY"]
        + p["CONV_LATENCY"])
    if tw_lat + p["ADD_LATENCY"] + mux_lat + p["CONV_LATENCY"] == 0:
        # fully combinational: the first clock edge (t = 0) is before the
        # first input value arrives, so cycle 0 shows the all-zero result
        outs[0] = [[0] * 4 for _ in range(n)]
        sync_out[0] = 0

    result = {port: [[outs[t][k][c] for k in range(n)] for t in range(cycles)]
              for c, port in enumerate(LANE_OUT)}
    result["of"] = [sum(b << k for k, b in enumerate(flags[t])) for t in range(cycles)]
    result["sync_out"] = sync_out
    return result


def shift_pattern(rng, cycles):
    s, v, t = [], 0, 0
    while t < cycles:
        hold = rng.randrange(8, 40)
        s += [v] * hold
        v ^= 1
        t += hold
    return s[:cycles]


def gen_butterfly():
    name = "butterfly_direct"
    mdir = TEST_DATA / "FFTs" / name
    entries = []
    for n, (lanes, biplex, fft, coeffs, sp, rest, cycles, desc) in enumerate(BUTTERFLY_TESTS):
        p = P(BF, [lanes, biplex, fft, len(coeffs), coeffs[0],
                   coeffs[1] if len(coeffs) > 1 else 0, sp] + rest)
        rng = random.Random(f"{name}-{n}")
        iw = p["INPUT_BIT_WIDTH"]
        st = {port: [[rng.randrange(1 << iw) for _ in range(lanes)] for _ in range(cycles)]
              for port in LANE_IN}
        for t, x in enumerate([1 << (iw - 1), (1 << (iw - 1)) - 1, (1 << iw) - 1, 0]):
            for port in LANE_IN:
                st[port][t + 1] = [x] * lanes
        frame = (len(coeffs) << sp) if twiddle_type(p) == "general" else (1 << (fft - 1))
        st["sync_in"] = tw.sync_pulses(cycles, frame)
        st["shift"] = shift_pattern(rng, cycles)
        out = m_butterfly(p, coeffs, st)

        d = mdir / f"simdata{n}"
        d.mkdir(parents=True, exist_ok=True)
        full = dict(p)
        if twiddle_type(p) == "general":
            (d / "twiddle.mem").write_text("".join(
                line + "\n" for line in mem_lines(
                    twiddle_table(coeffs, fft, p["COEFF_BIT_WIDTH"]), p["COEFF_BIT_WIDTH"])))
            full["INIT_FILE"] = MEM_REL.format(n=n)
        (d / "params.json").write_text(json.dumps(dict(full, COEFFS=coeffs), indent=2) + "\n")
        for port in LANE_IN + ["sync_in", "shift"]:
            write_csv(d / f"sim_{port}.csv", st[port])
        for port in LANE_OUT + ["of", "sync_out"]:
            write_csv(d / f"sim_{port}.csv", out[port])
        entries.append((full, desc, coeffs, cycles, twiddle_type(p)))

    keys = BF
    lines = [
        f"# {name} test data", "",
        "`butterfly_direct` computes `a + b·w` and `a − b·w` through the twiddle "
        "variant that casper's selection rule picks for `Coeffs` (column "
        "*Twiddle*), then shifts (dynamic `shift` input, hardcoded `DOWNSHIFT`, "
        "or bit growth), requantizes to `BIN_PT_IN` and flags overflow per lane. "
        "`sync_in` pulses once per coefficient frame (plus one early re-sync); "
        "`shift` toggles every 8–39 cycles. Cycles 1–4 drive the extreme words "
        "on every lane, the rest are seeded random.", "",
        "Generated by `test_data/scripts/gen_butterfly_test_data.py`: a Python reference "
        "model of `butterfly_direct_init.m` on top of the twiddle reference "
        "models of `test_data/scripts/gen_twiddle_test_data.py` (not exported from "
        "MATLAB). `params.json` also records casper's `COEFFS`; "
        "`twiddle.mem` (twiddle_general only) comes from "
        "`rtl/FFTs/Twiddle/scripts/gen_twiddle_coeffs.py`. CSV rows are cycles, lane ports have "
        "`N_INPUTS` columns (lane 0 first), `sim_of.csv` holds the `of` bus as "
        "an integer (bit n = lane n); all values are raw unsigned bit patterns "
        "with the pre-edge read convention.", "",
        "| Test # | Directory | " + " | ".join(keys)
        + " | COEFFS | Twiddle | Cycles | Description |",
        "|" + "---|" * (len(keys) + 6),
    ]
    for n, (full, desc, coeffs, cycles, kind) in enumerate(entries):
        lines.append(f"| {n} | `simdata{n}` | " + " | ".join(str(full[k]) for k in keys)
                     + f" | {coeffs} | {kind} | {cycles} | {desc} |")
    (mdir / "test_data.md").write_text("\n".join(lines) + "\n")
    return toml("FFTs", name, [(full, desc) for full, desc, *_ in entries], SCRIPT)


def toml(category, name, sets, script):
    lines = [f"# test {name}", "[[simulations]]", f'dir = "{category}"', f'top = "{name}"',
             f'test_data_script = "{script}"']
    for p, desc in sets:
        lines.append(f"# {desc}")
        lines.append("[[simulations.parameters]]")
        lines += [f"{k} = " + (f'"{v}"' if isinstance(v, str) else str(v)) for k, v in p.items()]
    return "\n".join(lines)


def main():
    run_cli(__doc__, {"butterfly_direct": gen_butterfly, "convert_of": gen_convert_of})


if __name__ == "__main__":
    main()
