"""Generate test data for sample_and_hold, negedge_delay (Misc) and window_delay (Delays).

Cycle-level models of the casper_library diagrams (casper_library_misc.slx
SID 158 / 77, casper_library_delays.slx SID 240). Row i of every CSV is the
value driven before / read after clock edge i (pre-edge read convention):
outputs are computed from the state before edge i and the inputs of cycle i.

Besides the structural models, two behavioural checks run on every set:

* negedge_delay: dout(t) = OR(din(t-L) .. din(t)) | (t <= L-2), i.e. the
  last high input is stretched by L cycles, plus the power-on pulse;
* window_delay: dout(t) = din(t-DELAY) (din = 0 before cycle 0) whenever
  same-kind edges are at least DELAY-1 cycles apart, which the stimulus of
  the sets marked "spaced" guarantees.

Each simdataN/ gets params.json and sim_<port>.csv; test_data.md is written
per module.
"""

import json
import math
import random

import numpy as np

from common import TEST_DATA_ROOT, run_cli

SCRIPT = "gen_hold_window_test_data.py"


def write_set(d, params, ports):
    d.mkdir(parents=True, exist_ok=True)
    (d / "params.json").write_text(json.dumps(params, indent=2) + "\n")
    for name, vals in ports.items():
        np.savetxt(d / f"sim_{name}.csv", np.asarray(vals, dtype=np.int64), fmt="%d")


def toml_block(dir_, top, sets):
    lines = [f"# test {top}", "[[simulations]]", f'dir = "{dir_}"', f'top = "{top}"',
             f'test_data_script = "{SCRIPT}"']
    for p, desc, _ in sets:
        lines += [f"# {desc}", "[[simulations.parameters]]"]
        lines += [f"{k} = {v}" for k, v in p.items()]
    return "\n".join(lines)


def write_md(mdir, top, prose, sets, cycles):
    keys = list(sets[0][0].keys())
    lines = [f"# {top} test data", "", prose, "",
             f"Generated by `test_data/scripts/{SCRIPT}` from a cycle-level model of the "
             "casper_library diagram (not exported from MATLAB). Each `simdataN/` holds "
             "`params.json` (the testbench matches it against the DUT parameters) and one "
             "`sim_<port>.csv` per port, row i = value driven before / read after clock "
             "edge i.", "",
             "| Test # | Directory | " + " | ".join(keys) + " | Cycles | Description |",
             "|" + "---|" * (len(keys) + 4)]
    for n, (p, desc, _) in enumerate(sets):
        lines.append(f"| {n} | `simdata{n}` | " + " | ".join(str(p[k]) for k in keys)
                     + f" | {cycles[n]} | {desc} |")
    (mdir / "test_data.md").write_text("\n".join(lines) + "\n")


def level_runs(rng, cycles, lo, hi, start=0):
    """A 0/1 level signal with run lengths uniform in [lo, hi]."""
    out, v = [], start
    while len(out) < cycles:
        out += [v] * rng.randint(lo, hi)
        v ^= 1
    return out[:cycles]


# ───────────────────────────────────────────────────────── sample_and_hold
def m_sample_and_hold(p, sync, din):
    period = p["PERIOD"]
    nb = math.ceil(math.log2(period))
    cnt, en_d, q = 0, 0, 0
    out = []
    for s, x in zip(sync, din):
        clr = int(cnt >= period - 1) | s
        out.append(q)
        if en_d:
            q = x
        en_d = clr
        cnt = 0 if clr else (cnt + 1) % (1 << nb)
    return out


def gen_sample_and_hold():
    mdir = TEST_DATA_ROOT / "Misc" / "sample_and_hold"
    specs = [
        (dict(PERIOD=8, BITWIDTH=8), "Period 8: free-running resample, syncs restart the period"),
        (dict(PERIOD=5, BITWIDTH=4), "Period 5 (not a power of 2, 3-bit counter)"),
        (dict(PERIOD=2, BITWIDTH=16), "Period 2: smallest legal period"),
        (dict(PERIOD=1024, BITWIDTH=32), "Mask default period 1024, 32-bit data"),
    ]
    sets, cycles = [], []
    for n, (p, desc) in enumerate(specs):
        rng = random.Random(f"sample_and_hold-{n}")
        cyc = 3 * p["PERIOD"] + 200 if p["PERIOD"] > 64 else 400
        sync = [0] * cyc
        t = rng.randint(3, 10)
        while t < cyc:
            sync[t] = 1
            # mostly sparse, sometimes closer than the period or back to back
            t += rng.choice([1, 2, p["PERIOD"] // 2 + 1, 3 * p["PERIOD"], 5 * p["PERIOD"] + 3])
        din = [rng.randrange(1 << p["BITWIDTH"]) for _ in range(cyc)]
        write_set(mdir / f"simdata{n}", p,
                  {"sync": sync, "din": din, "dout": m_sample_and_hold(p, sync, din)})
        sets.append((p, desc, None))
        cycles.append(cyc)
    write_md(mdir, "sample_and_hold",
             "`sample_and_hold` registers `din` one cycle after each `sync` and, between "
             "syncs, every `PERIOD` cycles. Syncs are sparse with a few back-to-back and "
             "closer-than-period ones; `din` is random.", sets, cycles)
    return toml_block("Misc", "sample_and_hold", sets)


# ─────────────────────────────────────────────────────────── negedge_delay
def m_negedge_delay(p, din):
    L = p["PULSE_LEN"]
    nb = math.ceil(math.log2(L + 1))
    prev = cnt = d1 = 0
    out = []
    for x in din:
        ne = int(not x and prev)
        run = int(cnt <= L - 2)
        out.append(x | d1 | run)
        cnt = 0 if ne else ((cnt + 1) % (1 << nb) if run else cnt)
        prev = d1 = x
    return out


def check_negedge_delay(p, din, out):
    L = p["PULSE_LEN"]
    for t, o in enumerate(out):
        want = int(any(din[max(0, t - L):t + 1]) or t <= L - 2)
        assert o == want, (p, t)


def gen_negedge_delay():
    mdir = TEST_DATA_ROOT / "Misc" / "negedge_delay"
    specs = [(3, "Minimum pulse length 3"), (5, "Mask default 5"),
             (8, "Pulse length 8 (4-bit counter)"), (16, "Pulse length 16 (5-bit counter)")]
    sets, cycles = [], []
    for n, (L, desc) in enumerate(specs):
        rng = random.Random(f"negedge_delay-{n}")
        p = dict(PULSE_LEN=L)
        cyc = 500
        # runs shorter and longer than L, one input that starts high
        din = level_runs(rng, cyc, 1, 2 * L + 3, start=n % 2)
        out = m_negedge_delay(p, din)
        check_negedge_delay(p, din, out)
        write_set(mdir / f"simdata{n}", p, {"din": din, "dout": out})
        sets.append((p, desc + ("; din high from power-on" if n % 2 else ""), None))
        cycles.append(cyc)
    write_md(mdir, "negedge_delay",
             "`negedge_delay` keeps `dout` high for `PULSE_LEN` cycles after `din` falls, "
             "and for the first `PULSE_LEN-1` cycles after power-on. `din` is a level "
             "signal with random run lengths shorter and longer than `PULSE_LEN`. The "
             "generator also checks `dout(t) = OR(din(t-PULSE_LEN..t)) | (t <= PULSE_LEN-2)`.",
             sets, cycles)
    return toml_block("Misc", "negedge_delay", sets)


# ──────────────────────────────────────────────────────────── window_delay
def m_sync_delay_step(cnt, x, n):
    """casper sync_delay (rtl/Delays/sync_delay.sv): returns (dout, next cnt)."""
    if n == 0:
        return x, 0
    return int(cnt == 1), (n if x else (cnt - 1 if cnt else 0))


def m_window_delay(p, din):
    D = p["DELAY"]
    prev = cr = cf = q = 0
    out = []
    for x in din:
        rise, fall = int(x and not prev), int(not x and prev)
        rd, cr = m_sync_delay_step(cr, rise, D - 1)
        fd, cf = m_sync_delay_step(cf, fall, D - 1)
        out.append(q)
        if fd:
            q = 0
        elif rd:
            q = rd
        prev = x
    return out


def gen_window_delay():
    mdir = TEST_DATA_ROOT / "Delays" / "window_delay"
    specs = [  # (DELAY, run lo, run hi, start, spaced, description)
        (10, 9, 30, 0, True, "Mask default 10, windows longer than DELAY-1"),
        (1, 1, 6, 0, True, "DELAY 1 (sync_delay length 0): one-cycle delay"),
        (2, 1, 8, 1, True, "DELAY 2, din high from power-on (rising edge at cycle 0)"),
        (16, 15, 40, 1, True, "DELAY 16, din high from power-on"),
        (12, 2, 9, 0, False, "DELAY 12, windows shorter than DELAY-1: sync_delay restarts"),
    ]
    sets, cycles = [], []
    for n, (D, lo, hi, start, spaced, desc) in enumerate(specs):
        rng = random.Random(f"window_delay-{n}")
        p = dict(DELAY=D)
        cyc = 500
        din = level_runs(rng, cyc, lo, hi, start=start)
        out = m_window_delay(p, din)
        ref = [0] * D + din[:cyc - D]
        if spaced:
            assert out == ref, (p, desc)
        else:
            assert out != ref, "non-spaced set should differ from a plain delay"
        write_set(mdir / f"simdata{n}", p, {"din": din, "dout": out})
        sets.append((p, desc, None))
        cycles.append(cyc)
    write_md(mdir, "window_delay",
             "`window_delay` delays a level signal by `DELAY` cycles with two `sync_delay`s "
             "on its edges. For the sets whose windows and gaps are at least `DELAY-1` "
             "cycles long the generator checks that `dout` is exactly `din` delayed by "
             "`DELAY`; the last set has shorter windows, where each new edge restarts the "
             "sync_delay counter and the output differs from a plain delay line (as in "
             "Simulink).", sets, cycles)
    return toml_block("Delays", "window_delay", sets)


if __name__ == "__main__":
    run_cli(__doc__, {"sample_and_hold": gen_sample_and_hold,
                      "negedge_delay": gen_negedge_delay,
                      "window_delay": gen_window_delay})
