#!/usr/bin/env python3
"""Generate test data for rtl/Delays/sync_delay and rtl/FFTs/fft_stage_n.

Expected outputs come from cycle-accurate Python reference models of the
casper_library behavior (sync_delay_init.m, fft_stage_n_init.m), not from
the RTL. fft_stage_n's butterfly reuses the reference model of
test_data/scripts/gen_butterfly_test_data.py (itself built on the twiddle models), and
its twiddle_general tables come from rtl/FFTs/Twiddle/scripts/gen_twiddle_coeffs.py.

Writes, per module, test_data/<Category>/<module>/simdataN/{params.json,
sim_<port>.csv[, twiddle.mem]} and test_data.md, and prints the matching
[[simulations]] blocks for tests/simulation.toml. CSV rows are clock cycles;
lane ports have N_INPUTS space-separated columns; values are raw unsigned
bit patterns (bus ports such as shift / of as integers).

Usage:
  python3 test_data/scripts/gen_fft_stage_test_data.py
"""

import json
import random
import sys
from pathlib import Path

from common import TEST_DATA_ROOT as TEST_DATA, run_cli          # also puts rtl/.../scripts on sys.path
from gen_twiddle_coeffs import mem_lines, twiddle_table            # rtl/FFTs/Twiddle/scripts/
from gen_butterfly_test_data import delay, m_butterfly, write_csv, P, toml
import gen_twiddle_test_data as tw

SCRIPT = Path(__file__).name


# ── sync_delay ──────────────────────────────────────────────────────────────

def m_sync_delay(din, delay_len):
    """Loadable down counter: load on din, count down, dout = (cnt == 1)."""
    if delay_len == 0:
        return [0] + din[1:]          # combinational; first edge precedes din
    cnt, out = 0, []
    for x in din:
        out.append(1 if cnt == 1 else 0)
        cnt = delay_len if x else max(cnt - 1, 0)
    return out


SYNC_DELAY_TESTS = [
    (0, "DELAY_LEN = 0: pass-through"),
    (1, "one cycle"),
    (5, "5 cycles"),
    (16, "16 cycles (counter needs 5 bits)"),
    (100, "100 cycles"),
]


def gen_sync_delay():
    name, cycles = "sync_delay", 512
    mdir = TEST_DATA / "Delays" / name
    sets = []
    for n, (dl, desc) in enumerate(SYNC_DELAY_TESTS):
        rng = random.Random(f"{name}-{n}")
        din = [0] * cycles
        t = 3
        while t < cycles:              # pulses mostly >= DELAY_LEN apart ...
            din[t] = 1
            t += rng.randrange(max(1, dl), 2 * dl + 8)
        for t in rng.sample(range(cycles), 4):   # ... plus a few that are not
            din[t] = 1
        p = {"DELAY_LEN": dl}
        d = mdir / f"simdata{n}"
        d.mkdir(parents=True, exist_ok=True)
        (d / "params.json").write_text(json.dumps(p, indent=2) + "\n")
        write_csv(d / "sim_din.csv", din)
        write_csv(d / "sim_out.csv", m_sync_delay(din, dl))
        sets.append((p, desc))
    lines = [
        f"# {name} test data", "",
        "`sync_delay` delays a sync pulse by `DELAY_LEN` cycles with a loadable "
        "down counter (a new pulse restarts the count, so pulses closer than "
        "`DELAY_LEN` collapse into the last one). Pulses are mostly spaced "
        "`DELAY_LEN`…`2·DELAY_LEN+7` cycles apart, plus 4 at random positions "
        "to exercise the restart.", "",
        "Generated by `test_data/scripts/gen_fft_stage_test_data.py` (Python reference "
        "model of `sync_delay_init.m`, not exported from MATLAB). Files: "
        "`sim_din.csv`, expected `sim_out.csv`, one value per cycle.", "",
        "| Test # | Directory | DELAY_LEN | Cycles | Description |",
        "|---|---|---|---|---|",
    ]
    for n, (p, desc) in enumerate(sets):
        lines.append(f"| {n} | `simdata{n}` | {p['DELAY_LEN']} | {cycles} | {desc} |")
    (mdir / "test_data.md").write_text("\n".join(lines) + "\n")
    return toml("Delays", name, sets, SCRIPT)


# ── fft_stage_n ─────────────────────────────────────────────────────────────

ST = ["N_INPUTS", "FFT_SIZE", "FFT_STAGE", "INPUT_BIT_WIDTH", "BIN_PT_IN", "COEFF_BIT_WIDTH",
      "BITGROWTH", "DOWNSHIFT", "HARDCODE_SHIFTS", "ADD_LATENCY", "MULT_LATENCY",
      "BRAM_LATENCY", "CONV_LATENCY", "QUANTIZATION", "OVERFLOW", "DELAYS_BRAM", "MAX_FANOUT"]

STAGE_TESTS = [
    (P(ST, [1, 4, 1, 18, 17, 18, 0, 0, 0, 1, 2, 1, 1, 1, 0, 0, 1]), 512,
     "16-point stage 1 (pass_through), register delays, fan latency 1"),
    (P(ST, [2, 4, 2, 18, 17, 18, 0, 0, 0, 1, 2, 1, 1, 1, 0, 1, 1]), 512,
     "stage 2 (twiddle_stage_2), 2 lanes, RAM delays"),
    (P(ST, [1, 4, 3, 18, 17, 18, 0, 0, 0, 1, 2, 2, 1, 2, 1, 1, 1]), 512,
     "stage 3 (twiddle_general), RAM delays with BRAM_LATENCY 2, round even + saturate"),
    (P(ST, [1, 4, 4, 18, 17, 18, 0, 0, 0, 1, 2, 2, 1, 1, 0, 1, 4]), 512,
     "last stage: ND = 1 < BRAM_LATENCY forces register delays, fan latency 0"),
    (P(ST, [3, 5, 3, 12, 11, 12, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2]), 512,
     "32-point stage 3, 3 lanes, bit growth, truncate"),
    (P(ST, [4, 5, 4, 26, 25, 18, 0, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1]), 512,
     "4 lanes × 26 bits (> 200-bit datapath: mux latency 2), hardcoded downshift"),
]

MEM_REL = "../../../test_data/FFTs/fft_stage_n/simdata{n}/twiddle.mem"
LANE_IN = ["in1_re", "in1_im", "in2_re", "in2_im"]
LANE_OUT = ["out1_re", "out1_im", "out2_re", "out2_im"]


def ceil_log_ratio(n, mf):
    """⌈log2(n) / max(1, log2(mf))⌉, exact (as the RTL constant function)."""
    if mf <= 2:
        return (n - 1).bit_length()
    k, p = 0, 1
    while p < n:
        p *= mf
        k += 1
    return k


def stage_timing(p):
    """(P, ND, MUX_LATENCY, uses RAM) exactly as fft_stage_n_init.m derives them."""
    f, s, iw, n = p["FFT_SIZE"], p["FFT_STAGE"], p["INPUT_BIT_WIDTH"], p["N_INPUTS"]
    nd = 1 << (f - s)
    use_bram = bool(p["DELAYS_BRAM"]) and nd >= p["BRAM_LATENCY"]
    min_lat = 1 if p["MAX_FANOUT"] <= 1 else 0
    if use_bram:
        riv = f - s
        word = 1 if riv >= 14 else 2 if riv >= 13 else 4 if riv >= 12 else \
            9 if riv >= 11 else 18 if riv >= 10 else 36
        n_brams = -(-(n * iw * 2) // word)
        fan = max(min_lat, ceil_log_ratio(n_brams, p["MAX_FANOUT"]) - 1)
        pre = fan + p["BRAM_LATENCY"]
    else:
        fan = max(min_lat, ceil_log_ratio(n, p["MAX_FANOUT"]) - 1)
        pre = fan
    mux = 1 if iw * n * 2 <= 200 else 2
    return pre, nd, mux, use_bram


def stage_coeffs(p):
    s = p["FFT_STAGE"]
    return [0] if s == 1 else list(range(1 << (s - 1)))


def m_fft_stage(p, st):
    n, cycles = p["N_INPUTS"], len(st["sync"])
    pre, nd, mux, _ = stage_timing(p)
    cnt_bits = p["FFT_SIZE"] - p["FFT_STAGE"] + 1
    lane_zero = [0] * n

    def lanes(prefix):
        return list(zip(st[prefix + "_re"], st[prefix + "_im"]))

    zero = (lane_zero, lane_zero)
    x1 = delay(lanes("in1"), pre, zero)
    x2 = delay(lanes("in2"), pre + nd, zero)
    sync_d = delay(st["sync"], pre, 0)

    cnt, m1, m0 = 0, [], []
    for t in range(cycles):
        sel = cnt >> (cnt_bits - 1)
        m1.append(x2[t] if sel else x1[t])
        m0.append(x1[t] if sel else x2[t])
        cnt = 0 if sync_d[t] else (cnt + 1) % (1 << cnt_bits)
    a = delay(delay(m1, mux, zero), pre + nd, zero)
    b = delay(delay(m0, mux, zero), pre, zero)
    sync_bf = m_sync_delay(delay(sync_d, pre + mux, 0), nd)

    coeffs = stage_coeffs(p)
    bp = {k: p[k] for k in ["N_INPUTS", "FFT_SIZE", "COEFF_BIT_WIDTH", "INPUT_BIT_WIDTH",
                             "BIN_PT_IN", "BITGROWTH", "DOWNSHIFT", "HARDCODE_SHIFTS",
                             "ADD_LATENCY", "MULT_LATENCY", "BRAM_LATENCY", "CONV_LATENCY",
                             "QUANTIZATION", "OVERFLOW", "MAX_FANOUT"]}
    bp.update(BIPLEX=1, N_COEFFS=len(coeffs), COEFF_0=0, COEFF_1=1,
              STEP_PERIOD=p["FFT_SIZE"] - p["FFT_STAGE"])
    bst = {"a_re": [list(r) for r, _ in a], "a_im": [list(i) for _, i in a],
           "b_re": [list(r) for r, _ in b], "b_im": [list(i) for _, i in b],
           "sync_in": sync_bf,
           "shift": [(s >> (p["FFT_STAGE"] - 1)) & 1 for s in st["shift"]]}
    bf = m_butterfly(bp, coeffs, bst)
    return {
        "out1_re": bf["apbw_re"], "out1_im": bf["apbw_im"],
        "out2_re": bf["ambw_re"], "out2_im": bf["ambw_im"],
        "of": delay([bf["of"][t] | st["of_in"][t] for t in range(cycles)], 1, 0),
        "sync_out": bf["sync_out"],
    }


def gen_fft_stage():
    name = "fft_stage_n"
    mdir = TEST_DATA / "FFTs" / name
    sets = []
    for n, (p, cycles, desc) in enumerate(STAGE_TESTS):
        rng = random.Random(f"{name}-{n}")
        iw, lanes, f = p["INPUT_BIT_WIDTH"], p["N_INPUTS"], p["FFT_SIZE"]
        st = {port: [[rng.randrange(1 << iw) for _ in range(lanes)] for _ in range(cycles)]
              for port in LANE_IN}
        st["sync"] = tw.sync_pulses(cycles, 1 << f)
        # shift bus: hold a random value for 20..60 cycles at a time
        st["shift"], t = [], 0
        while t < cycles:
            hold, v = rng.randrange(20, 60), rng.randrange(1 << f)
            st["shift"] += [v] * hold
            t += hold
        st["shift"] = st["shift"][:cycles]
        st["of_in"] = [rng.randrange(1 << lanes) if rng.random() < 0.05 else 0
                       for _ in range(cycles)]
        out = m_fft_stage(p, st)

        d = mdir / f"simdata{n}"
        d.mkdir(parents=True, exist_ok=True)
        full = dict(p)
        coeffs = stage_coeffs(p)
        if p["FFT_STAGE"] >= 3:
            (d / "twiddle.mem").write_text("".join(
                line + "\n" for line in mem_lines(
                    twiddle_table(coeffs, f, p["COEFF_BIT_WIDTH"]), p["COEFF_BIT_WIDTH"])))
            full["INIT_FILE"] = MEM_REL.format(n=n)
        pre, nd, mux, use_bram = stage_timing(p)
        (d / "params.json").write_text(json.dumps(dict(
            full, COEFFS=coeffs, DERIVED={"P": pre, "ND": nd, "MUX_LATENCY": mux,
                                          "RAM_DELAYS": int(use_bram)}), indent=2) + "\n")
        for port in LANE_IN + ["of_in", "sync", "shift"]:
            write_csv(d / f"sim_{port}.csv", st[port])
        for port in LANE_OUT + ["of", "sync_out"]:
            write_csv(d / f"sim_{port}.csv", out[port])
        sets.append((full, desc, cycles, (pre, nd, mux, use_bram)))

    lines = [
        f"# {name} test data", "",
        "`fft_stage_n` is one biplex FFT stage: a commutator (delays `P` and "
        "`P+ND`, a sync-reset counter, two muxes) pairs samples `ND = "
        "2^(FFT_SIZE-FFT_STAGE)` apart and feeds them to `butterfly_direct` "
        "with casper's stage coefficients. `sync` pulses once per "
        "`2^FFT_SIZE`-cycle frame plus one early re-sync; the `shift` bus holds "
        "random values for 20–59 cycles at a time; `of_in` has sparse random "
        "bits. The derived columns (`P`, `ND`, mux latency, RAM delays) are "
        "what `fft_stage_n_init.m` computes for each configuration.", "",
        "Generated by `test_data/scripts/gen_fft_stage_test_data.py`: a Python reference "
        "model of `fft_stage_n_init.m` on top of the butterfly reference model "
        "of `test_data/scripts/gen_butterfly_test_data.py` (not exported from MATLAB). "
        "`twiddle.mem` (stages ≥ 3) comes from `rtl/FFTs/Twiddle/scripts/gen_twiddle_coeffs.py`. "
        "CSV rows are cycles, lane ports have `N_INPUTS` columns (lane 0 "
        "first), bus ports are integers; raw unsigned bit patterns with the "
        "pre-edge read convention.", "",
        "| Test # | Directory | " + " | ".join(ST)
        + " | P | ND | MUX | RAM delays | Cycles | Description |",
        "|" + "---|" * (len(ST) + 8),
    ]
    for n, (full, desc, cycles, (pre, nd, mux, ub)) in enumerate(sets):
        lines.append(f"| {n} | `simdata{n}` | " + " | ".join(str(full[k]) for k in ST)
                     + f" | {pre} | {nd} | {mux} | {int(ub)} | {cycles} | {desc} |")
    (mdir / "test_data.md").write_text("\n".join(lines) + "\n")
    return toml("FFTs", name, [(full, desc) for full, desc, *_ in sets], SCRIPT)


def main():
    run_cli(__doc__, {"fft_stage_n": gen_fft_stage, "sync_delay": gen_sync_delay})


if __name__ == "__main__":
    main()
